const glossary = [
	{tag: "3d", description: "3D", category: "medium", definition:"Image rendered in 3D by a computer."},
	{tag: "abstract", description: "Abstract", category: "aspect", definition:"Nothing is recognisable."},
	{tag: "academism", description: "Academism", category: "movement", definition:""},
	{tag: "androcentric", description: "Androcentric", category: "impressionSemiObjective", definition:""},
	{tag: "animals", description: "Animals", category: "subject", definition:"Production centered on the representation of animals"},
	{tag: "anime", description: "Anime", category: "medium", definition:"Japanese animation cartoon"},
	{tag: "architecture", description: "Architecture", category: "medium", definition:""},
	{tag: "artdeco", description: "Art Deco", category: "movement", definition:""},
	{tag: "artnouveau", description: "Art Nouveau", category: "movement", definition:""},
	{tag: "baroque", description: "Baroque", category: "movement", definition:""},
	{tag: "bauhaus", description: "Bauhaus", category: "movement", definition:""},
	{tag: "cartoon", description: "Cartoon", category: "genre", definition:""},
	{tag: "character", description: "Character", category: "subject", definition:""},
	{tag: "children", description: "Children", category: "genre", definition:""},
	{tag: "cityscape", description: "Cityscape", category: "subject", definition:""},
	{tag: "clean", description: "Clean", category: "impressionSemiObjective", definition:"uncluttered"},
	{tag: "cloudscape", description: "Cloudscape", category: "subject", definition:""},
	{tag: "collage", description: "Collage", category: "medium", definition:""},
	{tag: "colorful", description: "Colorful", category: "impressionSemiObjective", definition:""},
	{tag: "comics", description: "Comics", category: "medium", definition:""},
	{tag: "cubism", description: "Cubism", category: "movement", definition:""},
	{tag: "dark", description: "Dark", category: "impressionSemiObjective", definition:""},
	{tag: "detailed", description: "Detailed", category: "aspect", definition:""},
	{tag: "digital", description: "Digital", category: "medium", definition:""},
	{tag: "drawing", description: "Drawing", category: "aspect", definition:""},
	{tag: "erotism", description: "Erotism", category: "genre", definition: "this adult theme"},
	{tag: "expressionism", description: "Expressionism", category: "movement", definition:""},
	{tag: "fantasy", description: "Fantasy", category: "genre", definition:""},
	{tag: "fashion", description: "Fashion", category: "medium", definition:""},
	{tag: "fauvism", description: "Fauvism", category: "movement", definition:""},
	{tag: "flatcolors", description: "Flat Colors", category: "aspect", definition:""},
	{tag: "futurism", description: "Futurism", category: "movement", definition:""},
	{tag: "geometric", description: "Geometric", category: "aspect", definition:""},
	{tag: "glitch", description: "Glitch", category: "aspect", definition: "Something feels wrong with this…"},
	{tag: "gore", description: "Gore", category: "aspect", definition:""},
	{tag: "graffiti", description: "Graffiti", category: "", definition:""},
	{tag: "graphicdesign", description: "Graphic Design", category: "movement", definition:""},
	{tag: "gynocentric", description: "Gynocentric", category: "impressionSemiObjective", definition:""},
	{tag: "highcontrast", description: "High contrast", category: "aspect", definition:""},
	{tag: "horror", description: "Horror", category: "genre", definition:""},
	{tag: "impressionism", description: "Impressionism", category: "movement", definition:""},
	{tag: "ink", description: "Ink", category: "medium", definition:"Drawing made with black ink and not colored"},
	{tag: "installation", description: "Installation", category: "medium", definition:""},
	{tag: "landscape", description: "Landscape", category: "subject", definition:""},
	{tag: "light", description: "Light", category: "", definition:"source of light well defined"},
	{tag: "lowcontrast", description: "Low contrast", category: "aspect", definition:""},
	{tag: "luminism", description: "Luminism", category: "movement", definition:"The light imbue the whole image in a kind of peaceful and transcendental way."},
	{tag: "magicrealism", description: "Magical Realism", category: "movement", definition:""},
	{tag: "manga", description: "Manga", category: "genre", definition:""},
	{tag: "messy", description: "Messy", category: "impressionSemiObjective", definition:""},
	{tag: "monochromatic", description: "Monochromatic", category: "aspect", definition:""},
	{tag: "nature", description: "Nature", category: "subject", definition:""},
	{tag: "nudity", description: "Nudity", category: "", definition:""},
	{tag: "passe", description: "Passé", category: "impressionSemiObjective", definition: "A bit old school, passé de mode"},
	{tag: "photography", description: "Photography", category: "medium", definition:""},
	{tag: "popart", description: "Pop Art", category: "movement", definition:""},
	{tag: "portrait", description: "Portrait", category: "subject", definition:""},
	{tag: "primitivism", description: "Primitivism", category: "movement", definition:""},
	{tag: "psychedelic", description: "Psychedelic", category: "impressionSemiObjective", definition:""},
	{tag: "realism", description: "Realism", category: "movement", definition:""},
	{tag: "renaissance", description: "Renaissance", category: "movement", definition:""},
	{tag: "rococo", description: "Rococo", category: "movement", definition:""},
	{tag: "romanticism", description: "Romanticism", category: "movement", definition:""},
	{tag: "scene", description: "Scene", category: "subject", definition:""},
	{tag: "scifi", description: "Sci-fi", category: "genre", definition:""},
	{tag: "sculpture", description: "Sculpture", category: "medium", definition:""},
	{tag: "seascape", description: "Seascape", category: "subject", definition:""},
	{tag: "space", description: "Space", category: "subject", definition:""},
	{tag: "stained glass", description: "Stained glass", category: "medium", definition:""},
	{tag: "stilllife", description: "Still life", category: "subject", definition:""},
	{tag: "streetart", description: "Street art", category: "subject", definition:""},
	{tag: "streetscape", description: "Streetscape", category: "subject", definition:""},
	{tag: "surrealism", description: "Surrealism", category: "movement", definition:""},
	{tag: "symbolism", description: "Symbolism", category: "movement", definition:""},
	{tag: "textile", description: "Textile", category: "medium", definition:""},
	{tag: "ukiyoe", description: "Ukiyo-e", category: "medium", definition:""},
	{tag: "vibrant", description: "Vibrant", category: "impressionSemiObjective", definition:""},
	{tag: "watercolor", description: "Watercolor", category: "medium", definition:""},
	{tag: "whimsical", description: "Whimsical", category: "impressionSemiObjective", definition:""},
	];
