const STRUCT_INSPIRATION = [
	/* TODO : move this to Artist section, when created. 
	"Draw inspiration from architectural designs by [architect 1], [architect 2].",
	"Draw inspiration from artists like [artist 1], [artist 2], and [artist 3].",
	"Draw inspiration from artists such as [artist 1], [artist 2], and [artist 3].",
	"Draw inspiration from designs by [designer 1], [designer 2], and [designer 3].",
	"Look to artists like [artist 1], [artist 2], and [artist 3] for inspiration.",
*/
	"It aim to capture the essence of %inspiration.",
	"It aim to capture the feeling of %inspiration.",
	"It is a representation of %inspiration.",
	"A %character is a representation of %inspiration.",
	"It is under the influence of %inspiration.",
	"It has been influenced by %inspiration.",
	"Influenced by %inspiration.",
	];

const BIB_INSPIRATION = {
	"Video Games": [
		"Minecraft", 
		"Super Mario", 
		"Monkey Island", 
		"Morrowind", 
		"Skyrim", 
		"Simcity", 
		"Popoulus", 
		"Lionhead Studio", 
		"8-bit games",
		"Alice Madness",
		"Anno 2070", 
		"Arcane League of Legend",
		"Aven Colony",
		"Bioshock",
		"Borderlands",
		"Galactic Civilizations", 
		"Doom", 
		"GLaDOS",
		"Castlevania",
		"Civilization", 
		"Cities Skylines", 
		"Darkest Dungeon", 
		"Portal",
		"Dwarf Fortress",
		"Deponia", 
		"Dune game", 
		"Fallout",  
		"Elite Dangerous", 
		"Frost Punk", 
		],
	"Movies": [
		"2001 Space Odyssey",
		"Shinning",
		"Back to the Futur",
		"Alien",
		"Predator",
		"The thing",
		"Leviathan",
		"Jaws",
		"Dune (1984)",
		"Dune (2022)", 
		"Game of Thrones",
		"Ghost in the shell",
		"70s science fiction",
		"Alien (1979)",
		"Harry Potter",
		"Interstellar",
		"Jurassic Parc",
		"Jurassic World", 
		"Lawrence of Arabia",
		"Lord of the ring",
		"Avatar", 
		"Avengers",
		"Blade Runner", 
		"Blade Runner 2049",
		"Day of the dead",
		"80s science fiction",
		"A Clockwork Orange (1971)",
		],
	"Animation/Cartoon": [
		"Alice in wonderland",
		"Fantastic Planet",
		"Ghost in the shell", 
		"Dragon Ball Z",
		"Avatar The Last Airbender",
		"Coraline",
		],
	"Years": [
		"-1000 BC",
		"1000 AD",
		"1500s",
		"1600s",
		"1700s",
		"1800s",
		"1900s",
		"1910s",
		"1920s",
		"1930s",
		"1940s",
		"1950s",
		"1960s",
		"1970s",
		"1980s",
		"1990s",
		"2000",  
		],
	"Space": [
		"2001 Space Odyssey", 
		],
	"Movie Directors": [
		"Alfonso Cuaron", 
		"Ang Lee", 
		"Baz Luhrmann", 
		"Christopher Nolan", 
		"Darren Aronofsky", 
		"David Cronenberg", 
		"David Fincher", 
		"David Lynch", 
		"Guillermo Del Toro", 
		"James Cameron",
		"Jane Campion", 
		"Kathryn Bigelow", 
		"Martin Scorsese", 
		"Pedro Almodovar", 
		"Quentin Tarantino", 
		"Sofia Coppola", 
		"Spike Lee", 
		"Stanley Kubrick", 
		"Steven Spielberg", 
		"Terrence Malick", 
		"Tim Burton", 
		"Wes Anderson", 
		],
	"Toys": [
		"Artdolls",
		"Barbie doll",
		"Lego minifigure",
		"Funkopop",
		],
	"Comics": [
		"DC Comics",
		"Garfield",
		],
	"Manga / Anime" : [
		"Saint Seiya", 
		"UFO Robo Grendizer", 
		"Ranma 1/2 ½ Nettou Hen", 
		"Taiyou no Ko Esteban", 
		"Doragon Bouru Zetto", 
		"Doragon Bôru", 
		"Uchuu Densetsu Ulysses 31", 
		"City Hunter", 
		"Space Cobra", 
		"Meitantei Holmes", 
		"Waga seishun no Arcadia - Mugen kidô SSX | Albator 84", 
		"Uchuu Kaizoku Captain Harlock", 
		"Captain Tsubasa", 
		"Cat's Eye", 
		"Tom Sawyer no Bouken", 
		"Hokuto no Ken", 
		"Kerokko Demetan", 
		"Lupin Sansei", 
		"Ginga Patrol PJ", 
		"Kidou Senshi Gundam 0080 : Pocket no Naka no Sensou", 
		"Chôjikû Yôsai Macross", 
		"Kimagure Orange Road", 
		"Mahou no Princess Minky Momo", 
		"Kidou Keisatsu Patlabor", 
		"Choujikuu Yousai Macross", 
		"Maison Ikkoku", 
		"Nils no Fushigi na Tabi", 
		"High School! Kimengumi", 
		"Teenage Mutant Ninja Turtles", 
		"DuckTales", 
		"Jayce and the Wheeled Warriors", 
		"Disney's Adventures of the Gummi Bears", 
		"The Smurfs", 
		"Thundercats", 
		],
	"Uncategorized (yet)":[
		"Bengal art",
		"Body worlds",
		"Blue Man Group",
		"Burlesque",
		"Burning Man", 
		"Carmina Burana",
		"Cirque du Soleil",
		"Danny Phantom",
		"Dexter's Lab",
		"Digimon", 
		"Disney",
		"DnD style",
		"Dreamworks",
		"Dungeon and Dragon, D&D",
		"Dungeon Master",
		"Femen", 
		"H.P. Lovecraft",
		"Hans Talhoffer fight book", 
		"Horizon Chase Turbo", 
		"How to train your dragon",
		"Howl’s Moving Castle",
		"Instagram",
		"International Typography",
		"Jack the ripper",
		"Johnny Bravo",
		"Jotun", 
		"Jules Verne",
		"Justice League", 
		"Kentucky Fried Chicken",
		"Magic The Gathering", 
		"Marvel comics",
		"Mass Effect", 
		"Matrix", 
		"Metropolis", 
		"Minecraft", 
		"Necronomicon",
		"Nendoroid figure",
		"Nosferatu", 
		"Nosferatu",
		"Oriental Chinese Style", 
		"Overwatch", 
		"Pan's Labyrinth",
		"Pixar",
		"Pizza Hut",
		"Pokemon", 
		"Pokémon",
		"Powerpuff Girls",
		"Pride & Prejudice",
		"Rampo Kitan", 
		"Rick and Morty",
		"Scooby Doo", 
		"Shrek",
		"Simcity", 
		"Sin City",
		"Siyah Qalam",
		"Skullgirls",
		"Slenderman",
		"Sonic the Hedgehog",
		"Spaceghost Coast to Coast",
		"Spongebob Squarepants",
		"Star Trek", 
		"Star Wars", 
		"Star Wars",
		"Starbucks",
		"Stardew Valley",
		"Steven Universe", 
		"Stranger Things",
		"Studio Ghibli",
		"Suicide girls",
		"Super Mario Bros.",
		"Super Mario",
		"Surviving Mars", 
		"Tarot",
		"Tetris", 
		"The Corpse Bride", 
		"The Long Dark", 
		"The nightmare before christmas",
		"The pillars of the earth", 
		"The Shining (1980)", 
		"The Simpsons",
		"The Thing (Carpenter)", 
		"Tijuana bible",
		"Total Drama",
		"Tototro", 
		"Toy Story",
		"Treasure Planet",
		"Trolls",
		"Tron",
		"Ukiyo-e", 
		"Vinyl figurine",
		"Voynish",
		"Warcraft",
		"Willow", 
		"Wipeout XL", 
		"Wolfenstein", 
		"Xianxia", 
		"Young Justice",
		"Zelda Wind Waker",
		"Zodiac signs",

		],

};

/* ["Lowbrow", ["arts",]], */


