const BIB_CELEB = {
	"Politics": [
		"Angela Merckel",
		"Emmanuel Macron",
		"Louis Michel",
		"Vladimir Poutine",
		],
	"Actor" : [
		"Adam Driver",
		"Bill Murray",
		"Bruce Willis",
		"Benedict Cumberbatch",
		"Dustin Hoffman",
		"Elijah Wood",
		"Ewan McGregor",
		"Forest Whitaker",
		"Gary Oldman",
		"George Takei",
		"Georges Cloney",
		"Harisson Ford",
		"Hugh Laurie",
		"Hugo Weaving",
		"Ian McKellen",
		"Jack Nicholson",
		"Jack Quaid",
		"Jason Isaacs",
		"Jason Momoa",
		"Jason Statham",
		"Jeff Bridges",	
		"Jeff Goldblum",
		],
	"Actress" : [
		"Amanda Plummer",
		"Amanda Tapping",
		"Angelina Jolie",
		"Marylin Monroe",
		"Jenna Ortega",
		"Christina Ricci",
		"Chelsea Peretti",
		"Charlize Theron",
		"Cate Blanchett",
		"Carrie Fisher", 
		"Billie Piper",
		"Cameron Diaz",
		"Claudia Black",
		"Clea DuVall",
		],
	"Singer" : [
		"Elvis Presley",
		],
	"Singeress" : [
		"Rihanna",
		"Marylin Monroe",
		"Björk",
		],
	"Sciences" : [
		"Albert Einstein",
		"Isaac Newton",
		"Charles Darwin",
		"Richard Hawking",
		"Dmitri Mendeleev",
		"Mikhail Lomonosov",
		"Thomas Edison",
		"Nikola Tesla",
		"Marie Curie",
		"Ada Lovelace",
		"Lise Meitner",
		"Henrietta Swan Leavitt",
		"Barbara Mcclintock",
		"Rachel Carson",
		"Chien-Shiung Wu",
		"Katherine Johnson",
		"Rosalind Franklin",
		"Jane Goodall",
		"Mae Jemison",
		"Emmanuelle Charpentier",
		],
	"Internet" : [
		"Boxxy",
		]
};



/*
	actor: [
		"Aaron Eckhart",
		"Adam Scott",
		"Alex Kingston",
		"Andre Braugher",
		"Antony Starr",
		"Mario Lopez",
		"Arthur Darvill",
		"Avery Brooks",
		"B. D. Wong",
		"Ben Browder",
		"Bill Pullman",
		"Billy Boyd",
		"Brat Pitt",
		"Bruce McGill",
		"Carles Dierkop",
		"Casper Van Dien",
		"Chace Crawford",
		"Chadwick Boseman",
		"Chris Evans",
		"Chris Hemsworth",
		"Chris Pratt",
		"Christopher Judge",
		"Christopher Lee",
		"Christopher Lloyd",
		"Colin Firth",
		"Crispin Glover",
		"D. B. Woodside",
		"David Cronenberg",
		"Dan Aykroyd",
		"Dana Elcar",
		"Daniel Radclif",
		"Danny Trejo",
		"David Hewlett",
		"David Tennant",
		"David Warner",
		"Deforest Kelley",
		"Diego Luna",
		"DJ Qualls",
		"Dominic Monaghan",
		"Don S. Davis",

		"Earl Boen",
		"Edward Norton",
		"Eric Szmanda",
		"Ernie Hudson",
		"Gary Dourdan",
		"George Eads",
		"Ian Holm",
		"J. K. Simmons",
		"Jack Cassidy",
		"Jake Busey",
		"James Earl Jones",
		"James Rebhorn",
		"Jason Biggs",
		"Jason Mantzoukas",
		"Jeffrey Hunter",
		"Jeremy Renner",
		"Jesse Spenser",
		"Jim Parsons",
		"John Boyega",
		"John Candy",
		"John Cho",
		"John Cleese",
		"Johnny Galecki",
		"Judd Hirsch",
		"Karl Urban", 
		"Keanu Reeves",
		"Kevin Spacey",
		"Kevin Sussman",
		"Kunal Nayyar",
		"Kurtwood Smith",
		"Lance Henriksen",
		"Laurence Fishburne",
		"Leonard Nimoy",
		"Liam Neeson",
		"Mads Mikkelsen",
		"Marg Helgenberger",
		"Mark Hamill",
		"Mark Lenard",
		"Martin Freeman",
		"Matt Lucas",
		"Matt Smith",
		"Michael Ironside",
		"Michael J. Fox",
		"Michael Shanks",
		"Miguel Ferrer",
		"Neil Patrick Harris",
		"Oded Fehr",
		"Omar Epps",
		"Omar Sy",
		"Orlando Bloom",
		"Oscar Isaac", 
		"Patrick McGoohan",
		"Patrick Stewart",
		"Paul Guilfoeyle",
		"Paul Newman",
		"Peter Capaldi",
		"Peter Dinklage",
		"Peter Falk",
		"Peter Jacobson",
		"Peter Weller",
		"Quentin Tarantino",
		"Ray Walston",
		"Ricardo Montalbán",
		"Richard Attenborough",
		"Richard Ayoade",
		"Richard Dean Anderson",
		"Rick Gervais",
		"Rick Moranis",
		"Riki Lindhome",
		"Robert David Hall",
		"Robert De Niro",
		"Robert Downey Jr.",
		"Robert Picardo",
		"Robert Redford",
		"Robert Shaw",
		"Robin Williams",
		"Ronny Cox",
		"Rowan Atkinson",
		"Sam Neil",
		"Samuel L. Jackson",
		"Sean Astin",
		"Sean Bean",
		"Sean Connery",
		"Seann William Scott",
		"Sigourney Weaver",
		"Simon Helberg",
		"Simon Pegg",
		"Stanley Tucci",
		"Stephen Fry",
		"Takeshi Kitano",
		"Ted Danson",
		"Ted Danson",
		"Terry Crews",
		"Thomas Brodie Sangster",
		"Tim Russ",
		"Timothée Chalamet",
		"Tobey Maguire",
		"Tom Cruise",
		"Tom Ellis",
		"Tom Hanks",
		"Tom Hiddleston",
		"Tomer Kapon",
		"Tony Amendola",
		"Val Kilmer",
		"Viggo Mortensen",
		"Wallace Langham",
		"Walter Koening",
		"Warwick Davis",
		"Wayne Knight",
		"Will Smith",
		"Willem Dafoe",
		"William Petersen",
		"William Shatner",
		"Woody Harrelson",
		"Billy Jayne",
		"Corin Nemec",
		"Troy Slaten",
		"Abraham Benrubi",
		"Marylin Manson",
		"Graham McTavish",
		"Sean Connery",
		"Brad Pitt",
		"Matt Damon",
		"Tchéky Karyo",
		"Bruce Greenwood",
		"Delroy Lindo",
		"Andy Garcia",
		"Bernie Mac",
		"Casey Affleck",
		"Shaobo Qin",
		"Elliott Gould",
		"Scott Caan",
		"Eddie Jemison",
		"Shane West",
		"Topher Grace",
		"James Cromwell",
		"William H. Macy",
		"George Clooney",
		"Keir Dullea",
		"Mark Strong",
		"Stacy Keach",
		"Daniel Craig", 
		"Peter Stormare",
		"Pierce Brosnan",
		"Jeffrey Wright",
		"Wentworth Miller",
		"Dominic Purcell",
		"William Devane",
		"Joe Flanigan",
		"Wade Williams",
		"Timothy Dalton",
		"Christopher Walken",
		"James Earl Jones",
		"Neal McDonough",
		"William Fichtner",
		"Bob Balaban",
		"Ralph Fiennes",
		"Rami Malek",
		"Robert Knepper",
		"Pete Postlethwaite",
		"Robbie Coltrane",
		"Volker Prechtel",
		"David Anders",
		"Greg Grunberg",
		"Terry O'Quinn",
		"John de Lancie",
		"Dominique Pinon",
		"Roger Moore",
		"Jonathan Banks",
		"Gary Dourdan",
		"Dean Norris",
		"Michael Vartan",
		"Bradley Cooper",
		"Ron Rifkin",
		"Carl Lumbly",
		"Kevin Weisman", 
		"Victor Garber", 
		"Christian Slater",
		"Ron Perlman",
		"F. Murray Abraham",
		"Michael Lonsdale",
		"William Hickey",
		"Noah Wyle",
		"Anthony Edwards",
		"Eriq La Salle",
		"Paul McCrane",
		"Goran Višnjić",
		"Scott Grimes",
		],

actress: [
	"Robin Tunney",
	"Cameron Richardson",
	"Halston Sage",
	"Maura Tierney",
	"Penny Johnson Jerald",
	"Isabel Lucas",
	"Amy Smart",
	"Rachael Harris",
	"Robin Tunney",
	"Merrin Dungey",
	"Josie Totah",
	"Skai Jackson",
	"Elya Baskin",
	"Michael Habeck",
	"Aimee Garcia",
	"Aimee Lou Wood",
	"Ally Sheedy",
	"Alyson Hannigan", 

	"Anne Hathaway",
	"Anya Taylor Joy",
	"Asa Butterfield",
	"Aubrey Plaza",
	"Audrey Hepburn",
	"Audrey Tautou",
	"Jessica De Gouw",
	"Aya Cash",
	"Carrie-Anne Moss",
	"Celia Rose Gooding",
	"Chiaki Kuriyama",
	"Chloë Grace Moretz",
	"Christina Chong",

	"Colby Minifie",
	"Daisy Ridley",
	"Dakota Fanning",
	"Denise Richards",
	"Dua Saleh",
	"Elizabeth Olsen",
	"Emily Perkins",
	"Emily Watson",
	"Emma Bunton",
	"Emma Stone",
	"Emma Watson",
	"Emma Myers",
	"Emmanuelle Béart",
	"Evanna Lynch",
	"Fairuza Balk",
	"Franka Potente",
	"Geri Halliwell",
	"Gillian Anderson",
	"Gwyneth Paltrow", 
	"Halle Berry",
	"Helena Bonham Carter",
	"Hilary Swank",
	"Jameela Jamil",
	"Jemima Kirke",
	"Jennifer Connelly",
	"Jennifer Garner",
	"Jennifer Lawrence",
	"Jeri Ryan",
	"Jess Bush",
	"Joanne Whalley",
	"Jodie Foster",
	"Jorja Fox",
	"Judi Dench",
	"Julia Roberts",
	"Julianne Moore",
	"Juliette Lewis",
	"Kaley Cuoco",
	"Kate Micucci",
	"Kate Mulgrew",
	"Keira Knightley",
	"Kristen Bell",
	"Kristen Stewart",
	"Lady Gaga",
	"Laura Dern",
	"Laura Dern",
	"Laura Harris",
	"Lauren German",
	"Lauren Lapkus",
	"Lesley-Ann Brandt",
	"Letitia Wright",
	"Linda Hamilton",
	"Lisa Edelstein",
	"Liv Tyler",
	"Liz Vassey",
	"Lucy Liu",
	"Lupita Nyong'o",
	"Maggie Gyllenhaal",
	"Marion Cotillard",
	"Mayim Bialik",
	"Melanie Brown",
	"Melanie Chisholm",
	"Melissa McCarthy",
	"Melissa Navia",
	"Melissa Rauch", 
	"Meryl Streep",
	"Michaela Coel",
	"Michelle Yeoh",
	"Miley Cyrus",
	"Molly Ringwald",
	"Monica Bellucci",
	"Nana Visitor",
	"Nancy Allen",
	"Naomie Harris",
	"Natalie Portman",
	"Neve Campbell",
	"Nichelle Nichols",
	"Nicki Minaj",
	"Nicole de Boer",
	"Olivia Wilde",
	"Patricia Allison",
	"Penélope Cruz",
	"Rachael Harris",
	"Rooney Mara",
	"Rosario Dawson",
	"Sally Hawkins",
	"Sandra Bullock",
	"Sara Gilbert",
	"Scarlett Johansson",
	"Shelley Duvall",
	"Sofia Boutella",
	"Sophie Marceau",
	"Tig Notaro",
	"Tilda Swinton",
	"Riki Lindhome",
	"Torri Higginson",
	"Uma Thruman",
	"Victoria Beckham",
	"Winona Ryder",
	"Yolandi Visser",
	"Zendaya",
	],
nonbinary: [
	"Amandla Stenberg",
	"Asia Kate Dillon",
	"Blu del Barrio",
	"Elliot Page",
	"Emma Corrin",
	"Ian Alexander",
	"Jesse James Keitel",
	"Liv Hewson",
	"Misha Oshervich",
	"Nico Tortorella",
	"Ruby Rose",
	],
};

*/