const STRUCT_INSPIRATION = [
	/* TODO : move this to Artist section, when created. 
	"Draw inspiration from architectural designs by [architect 1], [architect 2].",
	"Draw inspiration from artists like [artist 1], [artist 2], and [artist 3].",
	"Draw inspiration from artists such as [artist 1], [artist 2], and [artist 3].",
	"Draw inspiration from designs by [designer 1], [designer 2], and [designer 3].",
	"Look to artists like [artist 1], [artist 2], and [artist 3] for inspiration.",
*/
	"It aim to capture the essence of %inspiration.",
	"It aim to capture the feeling of %inspiration.",
	"It is a representation of %inspiration.",
	"A %character is a representation of %inspiration.",
	"It is under the influence of %inspiration.",
	"It has been influenced by %inspiration.",
	"Influenced by %inspiration.",
	];

const BIB_INSPIRATION = {
	"Video Games": [
		"8-bit games",
		"Alice Madness",
		"Anno 2070", 
		"Arcane League of Legend",
		"Aven Colony",
		"Bioshock",
		"Borderlands",
		"Castlevania",
		"Cities Skylines", 
		"Civilization", 
		"Darkest Dungeon", 
		"Deponia", 
		"Doom", 
		"Dune game", 
		"Dungeon Master",
		"Dwarf Fortress",
		"Elite Dangerous", 
		"Fallout",  
		"Frost Punk", 
		"Galactic Civilizations", 
		"GLaDOS",
		"Horizon Chase Turbo",
		"Jotun", 
		"Lionhead Studio", 
		"Mass Effect", 
		"Minecraft", 
		"Minecraft", 
		"Monkey Island", 
		"Morrowind", 
		"Overwatch", 
		"Pokemon", 
		"Popoulus", 
		"Portal",
		"Simcity", 
		"Simcity", 
		"Skullgirls",
		"Skyrim", 
		"Slenderman",
		"Super Mario Bros.",
		"Super Mario",
		"Super Mario", 
		"Tetris", 
		"The Long Dark", 
		"The pillars of the earth", 
		"Warcraft",
		"Wipeout XL", 
		"Wolfenstein", 
		"Zelda Wind Waker",
		],

	"Board Games / Card / DnD" : [
		"DnD style",
		"Dungeon and Dragon, D&D",
		"Magic The Gathering", 
		],

	"Movies": [
		"2001 Space Odyssey",
		"70s science fiction",
		"80s science fiction",
		"A Clockwork Orange (1971)",
		"Alien (1979)",
		"Alien",
		"Avatar", 
		"Avengers",
		"Back to the Futur",
		"Blade Runner 2049",
		"Blade Runner", 
		"Day of the dead",
		"Dune (1984)",
		"Dune (2022)", 
		"Game of Thrones",
		"Ghost in the shell",
		"Harry Potter",
		"Interstellar",
		"Jaws",
		"Jurassic Parc",
		"Jurassic World", 
		"Lawrence of Arabia",
		"Leviathan",
		"Lord of the ring",
		"Matrix", 
		"Metropolis", 
		"Nosferatu", 
		"Pan's Labyrinth",
		"Predator",
		"Shinning",
		"Sin City",
		"Star Trek", 
		"Star Wars", 
		"Stranger Things",
		"The Shining (1980)", 
		"The Thing (Carpenter)", 
		"The thing",
		"Tron",
		"Willow", 
		],

	"Animation/Cartoon": [
		"Alice in wonderland",
		"Avatar The Last Airbender",
		"Coraline",
		"Dexter's Lab",
		"Digimon", 
		"Disney",
		"Dragon Ball Z",
		"Dreamworks",
		"Fantastic Planet",
		"Ghost in the shell", 
		"How to train your dragon",
		"Howl’s Moving Castle",
		"Johnny Bravo",
		"Pixar",
		"Pokemon",
		"Powerpuff Girls",
		"Rick and Morty",
		"Scooby Doo", 
		"Shrek",
		"Spongebob Squarepants",
		"Steven Universe", 
		"The Corpse Bride", 
		"The nightmare before christmas",
		"The Simpsons",
		"Total Drama",
		"Toy Story",
		"Treasure Planet",
		"Trolls",
		],

	"Years": [
		"-1000 BC",
		"1000 AD",
		"1500s",
		"1600s",
		"1700s",
		"1800s",
		"1900s",
		"1910s",
		"1920s",
		"1930s",
		"1940s",
		"1950s",
		"1960s",
		"1970s",
		"1980s",
		"1990s",
		"2000",  
		],

	"Space / SciFi": [
		"2001 Space Odyssey", 
		"Star Trek",
		"Star Wars",
		"Dr Who",
		],

	"Movie Directors": [
		"Alfonso Cuaron", 
		"Ang Lee", 
		"Baz Luhrmann", 
		"Christopher Nolan", 
		"Darren Aronofsky", 
		"David Cronenberg", 
		"David Fincher", 
		"David Lynch", 
		"Guillermo Del Toro", 
		"James Cameron",
		"Jane Campion", 
		"Kathryn Bigelow", 
		"Martin Scorsese", 
		"Pedro Almodovar", 
		"Quentin Tarantino", 
		"Sofia Coppola", 
		"Spike Lee", 
		"Stanley Kubrick", 
		"Steven Spielberg", 
		"Terrence Malick", 
		"Tim Burton", 
		"Wes Anderson", 
		],

	"Toys": [
		"Artdolls",
		"Barbie doll",
		"Funkopop",
		"Lego minifigure",
		"Nendoroid figure",
		"Vinyl figurine",
		],

	"Comics": [
		"DC Comics",
		"Garfield",
		"Justice League", 
		"Marvel comics",
		"Tijuana bible",
		"Sin City",
		],

	"Manga / Anime" : [
		"Captain Tsubasa", 
		"Cat's Eye", 
		"Choujikuu Yousai Macross", 
		"Chôjikû Yôsai Macross", 
		"City Hunter", 
		"Disney's Adventures of the Gummi Bears", 
		"Doragon Bouru Zetto", 
		"Doragon Bôru", 
		"DuckTales", 
		"Ginga Patrol PJ", 
		"High School! Kimengumi", 
		"Hokuto no Ken", 
		"Jayce and the Wheeled Warriors", 
		"Kerokko Demetan", 
		"Kidou Keisatsu Patlabor", 
		"Kidou Senshi Gundam 0080 : Pocket no Naka no Sensou", 
		"Kimagure Orange Road", 
		"Lupin Sansei", 
		"Mahou no Princess Minky Momo", 
		"Maison Ikkoku", 
		"Meitantei Holmes", 
		"Nils no Fushigi na Tabi", 
		"Rampo Kitan", 
		"Ranma 1/2 ½ Nettou Hen", 
		"Saint Seiya", 
		"Space Cobra", 
		"Studio Ghibli",
		"Taiyou no Ko Esteban", 
		"Teenage Mutant Ninja Turtles", 
		"The Smurfs", 
		"Thundercats", 
		"Tom Sawyer no Bouken", 
		"Totoro", 
		"Uchuu Densetsu Ulysses 31", 
		"Uchuu Kaizoku Captain Harlock", 
		"UFO Robo Grendizer", 
		"Waga seishun no Arcadia - Mugen kidô SSX | Albator 84", 
		],

	"Horror, Gore" : [
		"H.P. Lovecraft",
		"Meatball Machine",
		"Necronomicon",
		"Nosferatu",
		"The thing",
		"Tokyo Gore Police",
		],

	"Esoteric" : [
		"Tarot",
		"Voynish",
		"Zodiac signs",
		"Illuminati",
		],

	"Uncategorized (yet)":[
		"Bengal art",
		"Body worlds",
		"Blue Man Group",
		"Burlesque",
		"Burning Man", 
		"Carmina Burana",
		"Cirque du Soleil",
		"Danny Phantom",
		"Young Justice",
		"Femen", 
		"Hans Talhoffer fight book", 
		"Instagram",
		"International Typography",
		"Jack the ripper",
		"Jules Verne",
		"Kentucky Fried Chicken",
		"Pizza Hut",
		"Pride & Prejudice",
		"Sonic the Hedgehog",
		"Spaceghost Coast to Coast",
		"Starbucks",
		"Stardew Valley",
		"Suicide girls",
		"Surviving Mars", 
		"Oriental Chinese Style", 
		"Siyah Qalam",
		"Xianxia", 
		"Ukiyo-e", 
		],

};

/* ["Lowbrow", ["arts",]], */


