const BIB_IMAGETYPES = {
	"Drawing": [
		"An illustration",
		"A charcoal sketch",
		"A drawing",
		"A sketch",
		"A pen and ink drawing",
		"A quick sketch",
		],
	"Photo": [
		"A photograph",
		"A black and white photography",
		"A picture",
		"A movie still",
		],
	"CG": [
		"A concept art",
		"A digital collage",
		"A 3D rendering",
		"A vector drawing",
		"A speed painting",
		"A digital painting",
		"A digital artwork",
		"A digital manipulation",
		"A pixel art",
		"ASCII art", 
		"Fractal art", 
		"Glitch art", 
		"3D modeling", 
		"3D wireframe", 
		],
	"Plastic Arts": [
		"A concept art",
		"A charcoal drawing",
		"A pastel drawing",
		"A gouache painting",
		"A collage artwork",
		"A acrylic painting",
		"A spray paint and stencil artwork",
		"A pastel artwork",
		"A graphite and colored pencil illustration",
		"A oil pastel and acrylic painting",
		"A gouache and ink painting",
		"A collage and watercolor artwork",
		"A chalk and charcoal sketch",
		"A charcoal and pastel drawing",
		"A oil painting",
		"A watercolor painting",
		],
	"Engraving": [
		"A linocut print",
		"A woodcut engraving",
		"A wood carving",
		"A etching artwork",
		"A linocut and screenprint",
		"A metal engraving",
		"A woodblock print",
		"A lithograph print",
		],
	"Other": [
		"An old newspaper illustration",
		"A wall painting",
		"A mixed media piece",
		"A screenprint",
		"A mosaic piece",
		"A glass mosaic piece",
		"A graffiti",
		"A mixed media collage",
		"A fabric and thread embroidery",
		"A cyanotype print",
		"A monoprint",
		],
	"Sculpture": [
		"A sculpture",
		"A voxel sculpture",
		"A clay sculpture",
		"A wood sculpture",
		"A metal sculpture",
		"A paper sculpture",
		"A wireframe sculpture",
		"A papercraft artwork",
		],
	"Creative propositions from ChatGPT": [
		"A whimsical doodle",
		"A fantastical painting",
		"An otherworldly digital artwork",
		"A dreamlike illustration",
		"A surrealist collage",
		"A cosmic-inspired painting",
		"An abstract expressionist artwork",
		"A minimalist depiction",
		"A retro-inspired illustration",
		"A futuristic digital manipulation",
		"A steampunk-inspired artwork",
		"A neon-infused painting",
		"A psychedelic illustration",
		"A pop art-inspired artwork",
		"A street art graffiti piece",
		"A vintage-inspired print",
		"A mosaic of emotions",
		"A mixed reality artwork",
		"A glitch art-inspired digital creation",
		"A nature-inspired mandala artwork",
		],
};

const BINDING_IMAGETYPES = [
	"capturing",
	"depicting",
	"displaying",
	"featuring",
	"of",
	"portraying",
	"portraying",
	"representing",
	"representing",
	"showcasing",
	"showing",
	];