const STRUCT_RENDERING = [
	"Render the image in a %technique style.",
	"Render the image in a %technique style with a focus on lighting.",
	"Render the image in a %technique style with attention to textures.",
	"Rendered in a %technique style with great attention to detail.",
	"Rendered in an hybrid technique of %technique and %technique.",
	"Rendered as %technique.",
	"Rendered with caracteristics of %technique and %technique.",
	"The image should highlight its %technique features.",
	"The image should showcase its %technique qualities.",
	"With a focus on use of %technique.",
	];

const BIB_RENDERING = {
	"Architecture" : [	
		"Ionic",
		"Ancient Greek",
		"Ancient Roman",
		"Corinthian",
		"Doric",
		"Classical",
		"Gothic",
		"Romanesque",
		"Baroque",
		"Renaissance",
		"Neoclassical",
		"Victorian",
		"Art Deco",
		"Modernist",
		"Postmodern",
		"Art Nouveau",
		"Bauhaus",
		"Brutalist",
		"Deconstructivist",
		"Futurist",
		"International",
		"Minimalist",
		"Neomodern",
		"Organic",
		"Sustainable",
		],

	"Art movement" : [
		"Cubo-Futurism",
		"Dada collage",
		"De Stijl",
		"60s kitsch and psychedelia",
		"Abstract Expressionism",
		"Abstract Illusionism",
		"Aestheticism",
		"Afrofuturism",
		"American Romanticism",
		"Art Brut",
		"Art Deco",
		"Arte Povera",
		"Ashcan School painting",
		"Avant-garde",
		"Baroque",
		"Bauhaus",
		"Brutalism",
		"Cassette futurism",
		"Classical",
		"Conceptual Art",
		"Cubism",
		"Dadaism",
		"Environmental Art",
		"Expressionism",
		"Fauvism",
		"Figurativism",
		"Fluxus",
		"German Romanticism",
		"Graffiti Art",
		"Hyperrealism",
		"Impressionism",
		"Installation Art",
		"Land Art",
		"Lowbrow",
		"Luminism",
		"Macchiaioli",
		"Magic realism",
		"Minimalism",
		"Modernism",
		"Narrative realism",
		"Naturalism",
		"Neo-classical",
		"Neo-Expressionism",
		"Op Art",
		"Performance Art",
		"Photorealism",
		"Pointillisme",
		"Pop Art",
		"Positivism",
		"Post-impressionism",
		"Pre-raphaelite",
		"Realism",
		"Renaissance",
		"retro-futurism",
		"Rococo",
		"Roman",
		"Street Art",
		"Stuckism",
		"Surrealism",
		"Symbolism",
		"Tenebrism",
		"Tonalism",
		"Vienna Sucession",],

	"Coloring" : [
		"chromatic aberration",
		"cyanotype",
		"DayGlo",
		"infrared",
		"neon",
		"primary colors",
		"golden hour",
		"at night",
		"at dawn",
		"at high noon",
		"CMYK",
		"dripping colors",
		"protanomaly",
		"protanopia",
		"tritanomaly",
		"tritanopia",
		"contrasting colors",
		"color splash",
		"coloring book style",
		"acid colors",
		"vibrant color scheme",
		"alizarin",
		"xanthic", 
		],

	"Lightning" : [
		"ambient lighting",
		"back light",
		"beautifully lit",
		"bioluminiscent",
		"bokeh",
		"bottom light",
		"bright",
		"broad lighting",
		"butterfly lighting",
		"candle light",
		"caustic",
		"chiaroscuro lighting",
		"cinematic lighting",
		"clamshell lighting",
		"dappled lighting",
		"dense light rays",
		"dramatic lighting",
		"dynamic lighting",
		"Fill light",
		"Front light",
		"golden hour",
		"high key lighting",
		"incandescent",
		"key light",
		"light",
		"loop lighting",
		"low key lighting",
		"moody lighting",
		"narrow lighting",
		"ray tracing",
		"rembrandt lighting",
		"rim light",
		"shaders",
		"short lighting",
		"side light",
		"silhouette",
		"split lighting",
		"three-point lighting",
		"top light",
		"vignetting",
		"volumetric lighting",
		],

	"Dark stuff" : [
		"bloody",
		"cosmic horror",
		"cosmic nebulae",
		"creepy",
		"cryptic",
		"dark",
		"depressing",
		"eerie",
		"eerie",
		"eldritch",
		"enigmatic",
		"ethereal",
		"fantastical",
		"frightening",
		"ghostly",
		"ghoulish",
		"gory",
		"gothic",
		"gruesome",
		"haunting",
		"horrific",
		"horror",
		"lovecraftian",
		"lovecraftian",
		"macabre",
		"miserable",
		"mysterious",
		"occult",
		"scary",
		"sinister",
		"spooky",
		"supernatural",
		"terrifying",
		"unsettling",
		],

	"Detailed picture" : [
		"intricate",
		"complex",
		"detailed",
		"fine",
		"elaborate",
		"ornate",
		"refined",
		"meticulous",
		"delicate",
		"sophisticated",
		"careful",
		"precise",
		"intricate",
		"laborious",
		"elaborate",
		"exacting",
		"thorough",
		"sophisticated",
		"intricate",
		"convoluted",
		"fussy",
		"minuscule",
		"subtle",
		"finespun",
		"minute",
		],

	"Fashion trend" : [
		"animecore",
		"minecraftcore",
		"normcore",
		"pixelcore",
		"robloxcore",
		"sparklecore",
		"glitchcore",
		"unicorncore",
		"cottagecore", 
		"dark academia", 
		"weirdcore",
		"witchcore",

		"minimalism",
		"bohemian",
		"streetwear",
		"vintage",
		"preppy",
		"grunge",
		"sporty",
		"goth",
		"punk",
		"hipster",

		"stylish",
		"fashionable",
		"trendy",
		"chic",
		"modern",
		"contemporary",
		"sophisticated",
		"edgy",
		"unique",
		"cool",

		"Fendi",
		"harlequin",
		],

	"Medium" : [
		"35 mm photograph",
		"3d",
		"aboriginal art",
		"acrylic painting",
		"amigurumi",
		"anime",
		"art nouveau",
		"astrophotography",
		"board game",
		"bonsai",
		"cartoon",
		"clay",
		"claymation",
		"cloisonné",
		"coffee paint",
		"collage",
		"colored pencil art",
		"comatesque inlay",
		"comic strip",
		"crayon art",
		"CryEngine",
		"damascening inlay",
		"digital art",
		"diorama",
		"Doom engine",
		"drawn in MS paint",
		"Egyptian hieroglyphs",
		"embroidery",
		"fresco",
		"glitch art",
		"gothic art",
		"gouache",
		"graffiti",
		"graphic design",
		"graphic novel",
		"holography",
		"ikebana",
		"illuminated manuscript",
		"impasto",
		"ink drawing",
		"intarsia inlay",
		"isotype",
		"khatam inlay",
		"kintsugi",
		"kokedama",
		"Korean folk art",
		"latte art",
		"lineart",
		"manga",
		"manichaean artwork",
		"marimekko",
		"marquetry",
		"medieval parchment",
		"mixed media",
		"mosaic",
		"niello inlay",
		"oil and canvas",
		"oil painting",
		"optical illusion",
		"parchinkari inlay",
		"parquetry",
		"petroglyph",
		"photoshop",
		"pietra dura inlay",
		"pixel art",
		"Play-Doh",
		"polaroid",
		"porcelain",
		"Quake engine",
		"rendered in autodesk 3ds max",
		"rendered in cinema4d",
		"rendered in corel art",
		"rendered in houdini",
		"rendered in octane",
		"rendered in povray",
		"rendered in rtx",
		"rendered in vray",
		"sculpture",
		"shin-hanga",
		"shou sugi ban",
		"silk",
		"sketched",
		"stained glass",
		"still life",
		"stop motion",
		"street art",
		"telephoto lens",
		"tempera",
		"thangka",
		"tilt-shift",
		"tintype",
		"traditional Sámi art",
		"tunbridge ware",
		"Ukiyo-e",
		"underwater photography",
		"Unreal Engine",
		"vector art",
		"voxel art",
		"watercolor painting",
		"wooden",
		"x-ray photography",
		"zbrush",
		"cyclopean masonry",
		"low poly",
		"blueprint",
		"chiaroscuro",
		"ray tracing",
		"raytracing",
		"ambrotype",
		"calotype",
		"daguerreotype",
		"long exposure",
		"macro lens",
		"multiple exposure",
		"risograph",
		"camcorder effect",
		"fisheye lens",
		"lomography",
		],

	"Photography" : [
		"ambrotype",
		"bokeh",
		"prismatic",
		"calotype",
		"camcorder effect",
		"daguerreotype",
		"depth of field",
		"fisheye lens",
		"lomography",
		"long exposure",
		"long exposure",
		"monochromatic",
		"photorealistic",
		"RTX",
		"soft shaded",
		"shot on Nikon D750",
		"sharp focus",
		"super wide angle",
		"polarized light",
		"macro lens",
		"multiple exposure",
		"chromatic aberration",
		"aerial photograph",
		"atmospheric",
		"autochrome",
		"cinematic",
		"daguerrotype",
		"dehazed", 
		"desaturated",
		"depth of field (dof)",
		"double exposure",
		],

	"Settings" : [
		"1950s suburbia",
		"1900s",
		"1910s",
		"1920s",
		"1930s",
		"1940s",
		"1950s",
		"1950s suburbia",
		"1960s",
		"1970s",
		"1970s era",
		"1980s",
		"1990s",
		"2000s",
		"2010s",
		"Akkadian",
		"Ancient Egyptian",
		"Archean",
		"Assyrian",
		"at dusk",
		"autumn",
		"Aztec",
		"Babylonian",
		"Byzantine",
		"Carboniferous",
		"in Ancient Egypt",
		"in Ancient Greece",
		"in Ancient Rome",
		"in Egypt",
		"in France",
		"in Greece",
		"in India",
		"in Indonesia",
		"in Italy",
		"in Japan",
		"in Rome",
		"in the Central African Republic",
		"in the desert",
		"in the jungle",
		"in the swamp",
		"in the tundra",
		"Indian",
		"Indonesian",
		"spring",
		"summer",
		"winter",
		"Ancient Greek",
		"Ancient Roman",
		"at dawn",
		"at high noon",
		"at night",
		],

	"Video Games" : [
		"16-Bit",
		"Amiga 500 style",
		"Atari 2600 style",
		"NES style",
		"Demoscene",
		"pixel art",
		"2d sprite",
		"3d polygon",
		"hand-drawn",
		"cel-shaded",
		"claymation",
		"voxel",
		"low-poly",
		"vector graphics",
		"isometric",
		"top-down",
		"first-person",
		"third-person",
		"overhead",
		"point-and-click",
		"side-scrolling",
		"platformer",
		"roguelike",
		"visual novel",
		"graphic adventure",
		],

	"-punk" : [
		"steampunk",
		"steelpunk",
		"solarpunk",
		"seapunk",
		"stonepunk",
		"voidpunk",
		"rococopunk",
		"postcyberpunk",
		"paranormalpunk",
		"lunarpunk",
		"islandpunk",
		"forestpunk",
		"frostpunk",
		"cassettepunk",
		"catholicpunk",
		"atompunk",
		"biopunk",
		"clockpunk",
		"cloudpunk",
		"cyberpunk",
		"deathpunk",
		"decopunk",
		"dieselpunk",
		"dollpunk",
		],

	"Electronic music" : [
		"Acid House",
		"Bass House",
		"Boogie",
		"Chillwave",
		"Darkwave",
		"Deep House",
		"Disco",
		"Drum and Bass",
		"Dubstep",
		"Electro House",
		"Electro-Disco",
		"Electro-Funk",
		"Electro-Pop",
		"Electroclash",
		"Funk",
		"DMT",
		"Gangsta Rap",
		"Glowwave",
		"Grime",
		"Hip Hop",
		"House",
		"New Wave",
		"No Wave",
		"Progressive Trance",
		"R&B",
		"Retrowave",
		"Soul",
		"Sovietwave",
		"Synth-Pop",
		"Synthwave",
		"Tech House",
		"Techno Trance",
		"Techno",
		"Techno-Disco",
		"Techno-Pop",
		"Trance",
		"Vaporwave",
		],

	"Artistic techniques" : [
		"flat rounded design",
		"acrylic marbling art",
		"acrylic pour",
		"airbrush",
		"alcohol ink",
		"Batik",
		"alhambresque",
		"artwork",
		"oil pastel",
		"chalk",
		"concept art",
		"watercolor",
		"champlevé",
		"children's illustration",
		"cell shading",
		"chalk art",
		],

	"Material": [
		"etched metal",
		"etched stone",
		"glass",
		"marbling",
		"metallic",
		"Yosegi",
		"pyrography",
		],

	"Unclassed" : [
		"4k",
		"Nvidia RTX",
		"aesthetic",
		"album cover",
		"alien",
		"alternate dimensions",
		"apocalyptic",
		"artstation hq",
		"Assemblage",
		"award-winning",
		"axonometric",
		"basic",
		"beatnik",
		"beautiful",
		"behance HD",
		"behance",
		"biochemical",
		"biomorphic",
		"biophilic",
		"buff",
		"Cenozoic",
		"cgsociety",
		"chibi",
		"cityscape",
		"clutter",
		"cold",
		"Concept Art World",
		"crystalline lattice",
		"contest winner",
		"cool",
		"crystallized",
		"cyberdelic",
		"cubism",
		"cyberpop",
		"cymatics", /* motif d'ondes sonores sur une surface de sable */
		"dark fine art",
		"dark",
		"deserted",
		"desolate",
		"deviantart",
		"digital illustration",
		"doodle",
		"Dota style",
		"Dreamworks",
		"dutch golden age",
		"dystopian",
		"Edwardian",
		"Egyptian mythology",
		"Egyptian",
		"electric",
		"elegant",
		"empyrean",
		"en plein air",
		"encaustic",
		"enlightenment",
		"enso",
		"Eraserhead",
		"ethereal",
		"evil",
		"excited",
		"eye strain",
		"fantasy",
		"fashion editorial",
		"fauvism",
		"fearful",
		"feline",
		"ferrofluid",
		"field of view",
		"fine art",
		"fluo colors",
		"foreboding",
		"fractal manifold",
		"fractal",
		"fractalism",
		"French",
		"funk art",
		"furry",
		"futuresynth",
		"Futurism",
		"tyftt",
		"futuristic",
		"glamour shot",
		"glow in the dark",
		"gold leaf",
		"goth",
		"gouache painting",
		"graffiti",
		"Greek",
		"grim dark",
		"Gucci",
		"Hadean",
		"hallucinogenic",
		"haze filter",
		"Hellenistic",
		"hi-fructose",
		"vintage advertisement", 
		"high chroma",
		"retro",
		"high contrast",
		"high speed liquid photography",
		"holographic",
		"horror",
		"hot",
		"HQ",
		"hydrodipped", /* comme ces enjoliveurs trempés dans un motif */ 
		"hygge",
		"hyper detailed",
		"hyperpop",
		"Inca",
		"infectious",
		"intricate artwork",
		"iridescence",
		"isometric",
		"Kai Fine Art",
		"kaleidoscopic",
		"kawaii",
		"lath art",
		"Lego model",
		"lighting",
		"liminal space",
		"linocut",
		"liquid ink",
		"lithograph",
		"lofi",
		"lomo effect",
		"Lord of the Rings",
		"Louis Vuitton",
		"low contrast",
		"LSD",
		"mac and cheese",
		"macabre fine art",
		"macabre",
		"manga",
		"mariachi",
		"massurrealism",
		"masterpiece",
		"matte painting",
		"Mayan",
		"McDonald's",
		"Medieval",
		"Mediterranean",
		"Mesoamerican",
		"Mesozoic",
		"messy",
		"microscopic",
		"Minecraft",
		"minimalism",
		"miyabi",
		"MOBA style",
		"Monster Rancher",
		"morbid fine art",
		"Moulin Rouge!",
		"Mughal painting",
		"multiracial",
		"mummified",
		"mural",
		"Myst",
		"naive",
		"Native American art",
		"Native American mythology",
		"Navajo",
		"neon pastel",
		"octane",
		"oil on canvas",
		"oily",
		"Op art",
		"optical art",
		"organometallics",
		"ornate",
		"ossuary",
		"Outrun",
		"Overgrown",
		"Paleolithic",
		"Paleozoic",
		"Pantone",
		"papaya whip",
		"papercraft",
		"patchwork",
		"Pattachitra",
		"petroglyph",
		"Phoenician",
		"Pixar",
		"pixiv", /* sorte de deviantart pour la mangass */
		"polygonal",	
		"pong",
		"poster",
		"powerful",
		"Prada",
		"propaganda poster",
		"psilocybin",
		"psychedelic",
		"pyroclastic flow",
		"radiant",
		"Rajasthani painting",
		"reflective",
		"refraction",
		"rendered with Blender",
		"sad",
		"Salad Fingers",
		"sand painting",
		"sci-fi",
		"science fiction",			
		"scrapbooking",
		"screenprinting",
		"sepia",
		"serious",
		"sfumato",
		"shibui",
		"sketch",
		"soft grunge",
		"southern gothic",
		"soviet poster",
		"splash art",
		"splatter art",
		"spooky",
		"stereo",
		"sticker",
		"stunning",
		"Sumerian",
		"Taco Bell",
		"Tanjore",
		"Tarot card",
		"tetris",
		"thalassophobia",
		"the matrix",
		"Toonami",
		"traditional Haida art",
		"trending on artstation",
		"trippy",
		"ultrarealistic",
		"unimaginable beauty",
		"Unsplash contest winnder",
		"velvia",
		"Versacci",
		"vintage illustration",
		"wabi-sabi", /* ~sobriété paisible */
		"warm",
		"watercolor",
		"woodblock print",
		"woodblock",
		"YouTube",
		"zoetrope",
		"zoomed out",
		],
};


