const BIB_ACTIONS = [
	"dancing in a %plant garden",
	"meditating between two %adj_chara %plant",
	"playing cards around a fire",
	"kissing a %character in %color",
	"holding his beloved %animal in his arm",
	"walking",
	"hold her umbrella",
	"turning around of a nude model lying in the sand",
	"standing and talking",
	"running and crying",
	"playing on a %material beach",
	"walking away under the rain",
	"sleeping under a %adj_chara %plant",
	"talking",
	"selling their wares",

	"bathing in front of a magma pool",
	"bathing in a lagoon",
	"bathing in nature",
	"being caught by a predator",
	"bending a metal rod",
	"bending at the hips over a group of %adj_chara %color skinned %character",
	"bending over a group of %character",
	"bending over a well and throwing stones",
	"breaking the fourth wall",
	"brewing beer in big copper cylinder",
	"building a %material house",
	"walking on the surface of the moon",
	"exploring an underwater cave",
	"reaching the summit of a volcano",
	"jumping out of an airplane above the clouds",
	"catching a wave in a flooded city street",
	"shredding a mountain of ice in Antarctica",
	"swimming with sharks in the open ocean",
	"leaping off a bridge into a canyon",
	"scaling a towering skyscraper",
	"jumping off a cliff into a deep ravine",
	"tackling a steep slope in the Himalayas",
	"navigating rough terrain in the desert",
	"performing tricks in a abandoned warehouse",
	"doing a backflip in a quarry",
	"running up a wall in a dense jungle",
	"performing a floor routine on a cruise ship",
	"executing a pirouette in a museum",
	"performing a stunt in a shopping mall",
	"breaking a board with a kick in a castle",
	"clearing a bar in a stadium",
	"executing a hop, skip, and jump in a field",
	"lifting a barbell in a gym",
	"raiding a building in a city",
	"tracking a mountain lion in the wilderness",
	"grinding on a rail in a parking garage",
	"hitting a jump in a blizzard",
	"pulling off a 360-degree spin in a pool",
	"performing a flip in a lake",
	"leaping from a building in a city",
	"executing a double flip in a circus tent",
	"fighting in a war-torn city",
	"tending to a field of crops",
	"clearing a bar in a park",
	"landing a jump on a beach",
	"casting a line into a river",
	"throwing a shot put in a backyard",
	"releasing a discus in a park",
	"launching a javelin in a field",
	"spinning a hammer in a garden",
	"galloping through a meadow",
	"flying through a thunderstorm",
	"speeding around a track in the rain",
	"practicing on a punching bag in a basement",
	"performing a flip off a diving board in a pool",
	"rescuing a cat from a tree",
	"chasing a suspect through a crowded market",
	"feeding a group of lions",
	"tracking a deer in the forest",
	"climbing a mountain trail",
	"carrying a dying sick child",
	"carrying a heavy %material trophee",
	"carrying only a light buckler to protect from the enemy",
	"climbing a mountain",
	"contempling a blood bath",
	"cooking for his friends",
	"cooking in a brand new kitchen",
	"covering bodies with blankets",
	"cracking open a big fruit with a %material tool",
	"crawling in a poorly lit sewer",
	"crossing a %color portal",
	"dancing around a bonfire under moonlight with %adj_chara %character",
	"dancing in the night",
	"dancing with fireflies",
	"digging a hole in the ground",
	"drawing on wall with chalk",
	"drinking and smoking while playing cards",
	"dripping blood all over the place in an artistic way",
	"drowning in dark waters",
	"exploring a field of giant %color luminous %plant",
	"fighting in a rest room",
	"fighting two %adj_chara %character",
	"fighting with a beast",
	"fighting with food",
	"fishing in a pond",
	"floating in the sky above a desert",
	"forging a metal object",
	"gently kissing",
	"grieving a lost love",
	"having fun with friends",
	"hiding in a %place",
	"holding a %material %object that emits pulsing energy",
	"holding a banded crossbow pointing at viewer",
	"holding a book above head",
	"holding a weapon, menacing someone",
	"holding an antique smoking gun revolver in his hands",
	"hugging a %character on large web of wery wide wire",
	"hunting in planet of %adj_chara %character",
	"joining a black cult",
	"kissing a %adj_chara %character",
	"kissing hands in a %place",
	"laughting alone",
	"lighting a fire",
	"looking at a syringe filled with blood",
	"looking at hands on a crowded station",
	"looking the viewer right in the eyes",
	"looking through an old window",
	"loosing a fight",
	"lying on a bed, being sick",
	"meditating in silence",
	"menacing a %character",
	"observing the city from a terrace",
	"petting a cute %color %character",
	"playing a %material musical instrument",
	"playing golf", 
	"playing with a gameboard",
	"ploughing a %adj_chara field",
	"posing suggestively in front of a painted backdrop",
	"reading a book in a comfy room",
	"reading newspaper in the deep ocean",
	"removing the seeds of a fruit",
	"riding a wheeled vehicule",
	"riding in the clouds",
	"running after a sleek fire %character with a suitcase",
	"running for life",
	"sitting on a marble tombstone",
	"sitting on floor with sunlight coming in through window",
	"sitting on roof in a %adj_chara city",
	"sleeping in a %adj_chara bed",
	"sleeping outside in a %place",
	"slowly removing clothes",
	"standing in %adj_chara water",
	"standing in a crop field a day of summer",
	"standing on a %color summoning circle, summoning demons",
	"studying in many old books",
	"swimming in a clear transparent water",
	"taking a midnight bath",
	"taking a shower",
	"taking care of a person",
	"taking care of childrens",
	"talking in front of a %material forge, some fire",
	"talking on television stage",
	"talking to a group of people",
	"teaching some precise task",
	"telling stories in front of a fire",
	"training hard with a weapon",
	"travelling in the land with friends",
	"walking a street under the rain",
	"walking in a salty ocean",
	"walking in swamp waters",
	"washing clothes",
	"washing hands",
	"wrappings a gift on a table",
	];