const PHRASES_LOOKALIKE = [
	"The main character resembles %celeb.",
	"The main character looks like %celeb.",
	"Played by %celeb.",
	"They are %celeb lookalikes.",
	"In the likeness of %celeb.",
	];

const BIB_CELEB = {
	"Politics": [
		"Abraham Lincoln",
		"Alexander the Great",
		"Angela Merkel",
		"Aristotle",
		"Aung San Suu Kyi",
		"Barack Obama",
		"Benazir Bhutto",
		"Bernie Sanders",
		"Bill Clinton",
		"Boris Johnson",
		"Catherine the Great",
		"Cleopatra",
		"Cristina Fernández de Kirchner",
		"David Cameron",
		"Dilma Rousseff",
		"Eleanor of Aquitaine",
		"Elizabeth of Russia",
		"Ellen Johnson Sirleaf",
		"Emmanuel Macron",
		"Empress Matilda",
		"Empress Wu Zetian",
		"Enrique Peña Nieto",
		"Franklin D. Roosevelt",
		"George Washington",
		"Golda Meir",
		"Hatshepsut",
		"Hillary Clinton",
		"Indira Gandhi",
		"Jacinda Ardern",
		"Joan of Arc",
		"Joe Biden",
		"Julius Caesar",
		"Justin Trudeau",
		"Justin Welby",
		"Kamala Harris",
		"King Henry VIII",
		"Louis Michel",
		"Mahatma Gandhi",
		"Margaret Thatcher",
		"Martin Luther King Jr.",
		"Mary Wollstonecraft",
		"Michelle Bachelet",
		"Napoleon Bonaparte",
		"Nelson Mandela",
		"Nicola Sturgeon",
		"Park Geun-hye",
		"Plato",
		"Queen Elizabeth I",
		"Queen Victoria",
		"Rafael Correa",
		"Sheikh Hasina",
		"Shinzo Abe",
		"Sojourner Truth",
		"Thomas Jefferson",
		"Tony Blair",
		"Vladimir Poutine",
		"William Shakespeare",
		"Winston Churchill",
		"Xi Jinping",
		],

	"Actor" : [
		"Aaron Eckhart",
		"Abraham Benrubi",
		"Adam Driver",
		"Adam Scott",
		"Andre Braugher",
		"Andy Garcia",
		"Anthony Edwards",
		"Antony Starr",
		"Armin Zimmermann",
		"Arthur Darvill",
		"Avery Brooks",
		"B. D. Wong",
		"Ben Browder",
		"Benedict Cumberbatch",
		"Bernie Mac",
		"Bill Murray",
		"Bill Pullman",
		"Billy Boyd",
		"Billy Jayne",
		"Bob Balaban",
		"Brad Pitt",
		"Bradley Cooper",
		"Brat Pitt",
		"Bruce Greenwood",
		"Bruce McGill",
		"Bruce Willis",
		"Carl Lumbly",
		"Carles Dierkop",
		"Casey Affleck",
		"Casper Van Dien",
		"Chace Crawford",
		"Chadwick Boseman",
		"Chris Evans",
		"Chris Hemsworth",
		"Chris Pratt",
		"Christian Slater",
		"Christopher Judge",
		"Christopher Lee",
		"Christopher Lloyd",
		"Christopher Walken",
		"Colin Firth",
		"Corin Nemec",
		"Crispin Glover",
		"D. B. Woodside",
		"Dan Aykroyd",
		"Dana Elcar",
		"Daniel Craig", 
		"Daniel Radclif",
		"Danny Trejo",
		"David Anders",
		"David Cronenberg",
		"David Hewlett",
		"David Tennant",
		"David Warner",
		"Dean Norris",
		"Deforest Kelley",
		"Delroy Lindo",
		"Diego Luna",
		"DJ Qualls",
		"Dominic Monaghan",
		"Dominic Purcell",
		"Dominique Pinon",
		"Don S. Davis",
		"Dustin Hoffman",
		"Earl Boen",
		"Eddie Jemison",
		"Edward Norton",
		"Elijah Wood",
		"Elliott Gould",
		"Eric Szmanda",
		"Eriq La Salle",
		"Ernie Hudson",
		"Ewan McGregor",
		"F. Murray Abraham",
		"Forest Whitaker",
		"Gary Dourdan",
		"Gary Dourdan",
		"Gary Oldman",
		"George Clooney",
		"George Eads",
		"George Takei",
		"Georges Cloney",
		"Goran Višnjić",
		"Graham McTavish",
		"Greg Grunberg",
		"Harisson Ford",
		"Hugh Laurie",
		"Hugo Weaving",
		"Ian Holm",
		"Ian McKellen",
		"J. K. Simmons",
		"Jack Cassidy",
		"Jack Nicholson",
		"Jack Quaid",
		"Jake Busey",
		"James Cromwell",
		"James Earl Jones",
		"James Rebhorn",
		"Jason Biggs",
		"Jason Isaacs",
		"Jason Mantzoukas",
		"Jason Momoa",
		"Jason Statham",
		"Jeff Bridges",	
		"Jeff Goldblum",
		"Jeffrey Hunter",
		"Jeffrey Wright",
		"Jeremy Renner",
		"Jesse Spenser",
		"Jim Parsons",
		"Joe Flanigan",
		"John Boyega",
		"John Candy",
		"John Cho",
		"John Cleese",
		"John de Lancie",
		"Johnny Galecki",
		"Jonathan Banks",
		"Judd Hirsch",
		"Karl Urban", 
		"Keanu Reeves",
		"Keir Dullea",
		"Kevin Spacey",
		"Kevin Sussman",
		"Kevin Weisman", 
		"Kunal Nayyar",
		"Kurtwood Smith",
		"Lance Henriksen",
		"Laurence Fishburne",
		"Leonard Nimoy",
		"Liam Neeson",
		"Mads Mikkelsen",
		"Marg Helgenberger",
		"Mario Lopez",
		"Mark Hamill",
		"Mark Lenard",
		"Mark Strong",
		"Martin Freeman",
		"Marylin Manson",
		"Matt Damon",
		"Matt Lucas",
		"Matt Smith",
		"Michael Ironside",
		"Michael J. Fox",
		"Michael Lonsdale",
		"Michael Shanks",
		"Michael Vartan",
		"Miguel Ferrer",
		"Neal McDonough",
		"Neil Patrick Harris",
		"Noah Wyle",
		"Oded Fehr",
		"Omar Epps",
		"Omar Sy",
		"Orlando Bloom",
		"Oscar Isaac", 
		"Patrick McGoohan",
		"Patrick Stewart",
		"Paul Guilfoeyle",
		"Paul McCrane",
		"Paul Newman",
		"Pete Postlethwaite",
		"Peter Capaldi",
		"Peter Dinklage",
		"Peter Falk",
		"Peter Jacobson",
		"Peter Stormare",
		"Peter Weller",
		"Pierce Brosnan",
		"Quentin Tarantino",
		"Ralph Fiennes",
		"Rami Malek",
		"Ray Walston",
		"Ricardo Montalbán",
		"Richard Attenborough",
		"Richard Ayoade",
		"Richard Dean Anderson",
		"Rick Gervais",
		"Rick Moranis",
		"Riki Lindhome",
		"Robbie Coltrane",
		"Robert David Hall",
		"Robert De Niro",
		"Robert Downey Jr.",
		"Robert Knepper",
		"Robert Picardo",
		"Robert Redford",
		"Robert Shaw",
		"Robin Williams",
		"Roger Moore",
		"Ron Perlman",
		"Ron Rifkin",
		"Ronny Cox",
		"Rowan Atkinson",
		"Sam Neil",
		"Samuel L. Jackson",
		"Scott Caan",
		"Scott Grimes",
		"Sean Astin",
		"Sean Bean",
		"Sean Connery",
		"Sean Connery",
		"Seann William Scott",
		"Shane West",
		"Shaobo Qin",
		"Sigourney Weaver",
		"Simon Helberg",
		"Simon Pegg",
		"Stacy Keach",
		"Stanley Tucci",
		"Stephen Fry",
		"Takeshi Kitano",
		"Tchéky Karyo",
		"Ted Danson",
		"Ted Danson",
		"Terry Crews",
		"Terry O'Quinn",
		"Thomas Brodie Sangster",
		"Tim Russ",
		"Timothy Dalton",
		"Timothée Chalamet",
		"Tobey Maguire",
		"Tom Cruise",
		"Tom Ellis",
		"Tom Hanks",
		"Tom Hiddleston",
		"Tomer Kapon",
		"Tony Amendola",
		"Topher Grace",
		"Troy Slaten",
		"Val Kilmer",
		"Victor Garber", 
		"Viggo Mortensen",
		"Volker Prechtel",
		"Wade Williams",
		"Wallace Langham",
		"Walter Koening",
		"Warwick Davis",
		"Wayne Knight",
		"Wentworth Miller",
		"Will Smith",
		"Willem Dafoe",
		"William Devane",
		"William Fichtner",
		"William H. Macy",
		"William Hickey",
		"William Petersen",
		"William Shatner",
		"Woody Harrelson",
		],

"Actress" : [
	"Aimee Garcia",
	"Aimee Lou Wood",
	"Alex Kingston",
	"Ally Sheedy",
	"Alyson Hannigan", 
	"Amanda Plummer",
	"Amanda Tapping",
	"Amy Smart",
	"Angelina Jolie",
	"Anne Hathaway",
	"Anya Taylor Joy",
	"Asa Butterfield",
	"Aubrey Plaza",
	"Audrey Hepburn",
	"Audrey Tautou",
	"Aya Cash",
	"Billie Piper",
	"Cameron Diaz",
	"Cameron Richardson",
	"Carrie Fisher", 
	"Carrie-Anne Moss",
	"Cate Blanchett",
	"Celia Rose Gooding",
	"Charlize Theron",
	"Chelsea Peretti",
	"Chiaki Kuriyama",
	"Chloë Grace Moretz",
	"Christina Chong",
	"Christina Ricci",
	"Claudia Black",
	"Clea DuVall",
	"Colby Minifie",
	"Daisy Ridley",
	"Dakota Fanning",
	"Denise Richards",
	"Dua Saleh",
	"Elizabeth Olsen",
	"Elya Baskin",
	"Emily Perkins",
	"Emily Watson",
	"Emma Bunton",
	"Emma Myers",
	"Emma Stone",
	"Emma Watson",
	"Emmanuelle Béart",
	"Evanna Lynch",
	"Fairuza Balk",
	"Franka Potente",
	"Geri Halliwell",
	"Gillian Anderson",
	"Gwyneth Paltrow", 
	"Halle Berry",
	"Halston Sage",
	"Helena Bonham Carter",
	"Hilary Swank",
	"Isabel Lucas",
	"Jameela Jamil",
	"Jemima Kirke",
	"Jenna Ortega",
	"Jennifer Connelly",
	"Jennifer Garner",
	"Jennifer Lawrence",
	"Jeri Ryan",
	"Jess Bush",
	"Jessica De Gouw",
	"Joanne Whalley",
	"Jodie Foster",
	"Jorja Fox",
	"Josie Totah",
	"Judi Dench",
	"Julia Roberts",
	"Julianne Moore",
	"Juliette Lewis",
	"Kaley Cuoco",
	"Kate Micucci",
	"Kate Mulgrew",
	"Keira Knightley",
	"Kristen Bell",
	"Kristen Stewart",
	"Lady Gaga",
	"Laura Dern",
	"Laura Dern",
	"Laura Harris",
	"Lauren German",
	"Lauren Lapkus",
	"Lesley-Ann Brandt",
	"Letitia Wright",
	"Linda Hamilton",
	"Lisa Edelstein",
	"Liv Tyler",
	"Liz Vassey",
	"Lucy Liu",
	"Lupita Nyong'o",
	"Maggie Gyllenhaal",
	"Marion Cotillard",
	"Marylin Monroe",
	"Maura Tierney",
	"Mayim Bialik",
	"Melanie Brown",
	"Melanie Chisholm",
	"Melissa McCarthy",
	"Melissa Navia",
	"Melissa Rauch", 
	"Merrin Dungey",
	"Meryl Streep",
	"Michael Habeck",
	"Michaela Coel",
	"Michelle Yeoh",
	"Miley Cyrus",
	"Molly Ringwald",
	"Monica Bellucci",
	"Nana Visitor",
	"Nancy Allen",
	"Naomie Harris",
	"Natalie Portman",
	"Neve Campbell",
	"Nichelle Nichols",
	"Nicki Minaj",
	"Nicole de Boer",
	"Olivia Wilde",
	"Patricia Allison",
	"Penny Johnson Jerald",
	"Penélope Cruz",
	"Rachael Harris",
	"Rachael Harris",
	"Riki Lindhome",
	"Robin Tunney",
	"Robin Tunney",
	"Rooney Mara",
	"Rosario Dawson",
	"Sally Hawkins",
	"Sandra Bullock",
	"Sara Gilbert",
	"Scarlett Johansson",
	"Shelley Duvall",
	"Skai Jackson",
	"Sofia Boutella",
	"Sophie Marceau",
	"Tig Notaro",
	"Tilda Swinton",
	"Torri Higginson",
	"Uma Thruman",
	"Victoria Beckham",
	"Winona Ryder",
	"Yolandi Visser",
	"Zendaya",
	],

"Non-binary celeb": [
	"Amandla Stenberg",
	"Asia Kate Dillon",
	"Blu del Barrio",
	"Elliot Page",
	"Emma Corrin",
	"Ian Alexander",
	"Jesse James Keitel",
	"Liv Hewson",
	"Misha Oshervich",
	"Nico Tortorella",
	"Ruby Rose",
	],

"Singer" : [
	"Adam Levine",
	"Billy Joel",
	"Bon Jovi",
	"Bono",
	"Boy George",
	"Bruce Springsteen",
	"Bruno Mars",
	"Bryan Adams",
	"Charlie Puth",
	"Chris Martin",
	"David Bowie",
	"Drake",
	"Ed Sheeran",
	"Elton John",
	"Elvis Presley",
	"Freddie Mercury",
	"George Michael",
	"Harry Styles",
	"Jason Derulo",
	"John Legend",
	"Justin Bieber",
	"Justin Timberlake",
	"Khalid",
	"Lionel Richie",
	"Michael Bublé",
	"Michael Jackson",
	"Mickael Jackson",
	"Morrissey",
	"Nick Jonas",
	"Paul McCartney",
	"Peter Gabriel",
	"Pharrell Williams",
	"Phil Collins",
	"Post Malone",
	"Prince",
	"Rick Astley",
	"Sam Smith",
	"Shawn Mendes",
	"Simon Le Bon",
	"Sting",
	"The Weeknd",
	"Usher",
	],

"Singeress" : [
	"Alanis Morissette",
	"Annie Lennox",
	"Belinda Carlisle",
	"Björk",
	"Celine Dion",
	"Cher",
	"Cyndi Lauper",
	"Debbie Gibson",
	"Enya",
	"Gloria Estefan",
	"Janet Jackson",
	"Janet Jackson",
	"Jewel",
	"Kate Bush",
	"Lisa Stansfield",
	"Madonna",
	"Mariah Carey",
	"Marylin Monroe",
	"Melissa Etheridge",
	"Natalie Merchant",
	"Pat Benatar",
	"Paula Abdul",
	"Paula Cole",
	"Rihanna",
	"Sade",
	"Shania Twain",
	"Sheryl Crow",
	"Stevie Nicks",
	"Tina Turner",
	"Toni Braxton",
	"Whitney Houston",
	"Whitney Houston",
	],

"Sciences" : [
	"Ada Lovelace",
	"Albert Einstein",
	"Barbara Mcclintock",
	"Charles Darwin",
	"Chien-Shiung Wu",
	"Dmitri Mendeleev",
	"Emmanuelle Charpentier",
	"Henrietta Swan Leavitt",
	"Isaac Newton",
	"Jane Goodall",
	"Katherine Johnson",
	"Lise Meitner",
	"Mae Jemison",
	"Marie Curie",
	"Mikhail Lomonosov",
	"Nikola Tesla",
	"Rachel Carson",
	"Richard Hawking",
	"Rosalind Franklin",
	"Thomas Edison",
	],

"Internet" : [
	"Boxxy",
	"Casey Neistat",
	"Colleen Ballinger",
	"Dan and Phil",
	"David Dobrik",
	"Grace Helbig",
	"James Charles",
	"Jenna Marbles",
	"Joji",
	"Lele Pons",
	"Lilly Singh",
	"Lilly Singh",
	"Liza Koshy",
	"Logan Paul",
	"Miranda Sings",
	"PewDiePie",
	"Shane Dawson",
	"Tanya Burr",
	"Trisha Paytas",
	"Tyler Oakley",
	"Zoella",
	]
};
