const BIB_HAIRS = {
	"Normal": [
		"long %color hair",
		"short %color hair",
		"curls of hair",
		"cut %color hair",
		"afro hair with curls",
		],
	"Cut": [
		"%color hair with elaborate updo hairstyle",
		"%color undercut hair",
		"%color short hair",
		"a bob",
		"a fringe",
		"a mullet",
		"pixie %color hair",
		"dreadlock hair",
		"topbun",
		"a ponytail",
		"a long beard",
		"braided hair",
		"pixie cut",
		"buzz cut",
		"a crab hairstyle",
		"cool medium length hairstyle",
		"emo cut %color hair",
		"elegant hairstyle",
		"shaved head",
		],
	"Decored / Accessories": [
		"%color hair with braids and jewelry",
		"%color colored hair",
		"curly %color electrified hair",
		"flowers in hair",
		"ribbons in hair", 
		"a cute hat",
		],
};

/*
let allHairStyles = [
	"bangs",
	"black and %color hair up in ponytails",
	"black and white hair",
	"bright shiny hair",
	"curly golden hair and golden freckles",
	"curly pastel %color hair and cute bangs",
	"dark curly hair",
	"dark graying hair",
	"eboy hair",
	"electric hair",
	"flaming hair",
	"fluffy hair",
	"glossy black hair",
	"glossy black hair", 
	"hair combed over",
	"hair in cornrows",

	"hair in fire",
	"hair over one eye",
	"hair pinned up in a bun",
	"hair with white streak",
	"jellyfish hair",
	"long acid %color africana dreadlocks hair",
	"long blond hair",
	"long braids",
	"long curly %color hair",
	"long curly fire hair",
	"long curly hair",
	"long dirty black hair",
	"long elegant black hair,",
	"long flowing hair",
	"long flowing light %color hair",
	"long flowing light black hair", 
	"long glowing white hair",
	"long hair", 
	"long silverwhite hair with braids and buns",
	"long straight %color hair in a high ponytail",
	"long straight black haired ",
	"long straight hair", 
	"long stylish straight hair",
	"long volumnous silky %color hair",
	"long wavy %color hair",
	"luscious hair ",
	"lustrous hair",
	"luxurious %color hair",
	"luxurious hair covering one eye", 
	"majestic hairdo",
	"messy long %color hair",
	"necklength hair ",
	"orange undercut hair",
	"pastel %color hair",
	"pastel %color long curly hair",
	"plait hair",
	"raven hair",
	"shaved head",
	"short brunette hair",
	"short fluff blonde hair",
	"short hair",
	"shoulder length curly %color hair",
	"shoulder length curly hair",
	"silky hair",
	"silver hair",
	"snake hair",
	"spicky hair",
	"spiked %color hair",
	"straight grey neck length hair",
	"straight hair",
	"straight ruby red hair",
	"straight tomboy short %color hair",
	"styled hair",
	"super long hair",
	"thick messy %color hair cut short",
	"undercut haircut",
	"very long hair",
	"voluminous hair",
	"wavy blonde hair",
	"wavy hair",
	"wavy shortmedium hair",
	"white hair",
	"windswept hair",
	];

*/