const BIB_COLORS = {
	"Hair colors":[
		"blonde",
		"platinum",
		"dirty blonde",
		"golden blonde",
		"strawberry blonde",
		"red",
		"auburn",
		"copper",
		"mahogany",
		"brown",
		"light brown",
		"dark brown",
		"chestnut",
		"chocolate",
		"black",
		"gray",
		"silver",
		"white",
		"salt and pepper",
		"ombre",
		],
	"Natural colors": [
		"sky blue",
		"ocean blue",
		"grass green",
		"forest green",
		"leafy green",
		"sand beige",
		"desert sand",
		"earthy brown",
		"clay brown",
		"stone gray",
		"charcoal gray",
		"sunset orange",
		"canyon red",
		"autumn red",
		"sunflower yellow",
		"sunshine yellow",
		"cloud white",
		"snow white",
		"midnight black",
		"starlit navy"
		],
	"Metal color": [
		"silver",
		"gold",
		"copper",
		"bronze",
		"brass",
		"steel",
		"iron",
		"platinum",
		"pewter",
		"nickel",
		"rust",
		"titanium",
		"aluminum",
		"lead",
		"zinc",
		"chrome",
		"gunmetal",
		"rose gold",
		"white gold",
		"blackened steel",
		],

	"Primary colors (screen)": ["red", "blue", "green"],
	"Primary colors (print)": ["yellow", "cyan", "magenta", "black"],

	"Skins colors" : [
		"albino", 
		"almond",
		"beige",
		"bisque",
		"caramel",
		"chestnut",
		"cocoa",
		"coffee",
		"copper",
		"cream",
		"ebony",
		"fawn",
		"honey",
		"ivory",
		"mahogany",
		"mocha",
		"peach",
		"sable",
		"sienna",
		"tan",
		"wheat",
		],
	"Fruits & Vegetable": [
		"apricot", 
		"hazelnoot",
		"beet red",
		"carrot orange",
		"lemon yellow",
		"apple green",
		"kale green",
		"eggplant purple",
		"tomato red",
		"pumpkin orange",
		"blueberry blue",
		"pomegranate red",
		"cucumber green",
		"cherry red",
		"banana yellow",
		"grape purple",
		"watermelon pink",
		"mango orange",
		"cantaloupe orange",
		"kiwi green",
		"raspberry red",
		"corn yellow"],
	"Flowers": [
		"sunflower yellow",
		"lavender purple",
		"rose red",
		"daisy white",
		"iris blue",
		"poppy red",
		"peony pink",
		"chrysanthemum yellow",
		"hibiscus red",
		"marigold orange",
		"hydrangea blue",
		"tulip pink",
		"lily white",
		"orchid purple",
		"carnation pink",
		"zinnia orange",
		"gladiolus red",
		"daffodil yellow",
		"snapdragon pink",
		"anemone purple",],
	"Mineral" : [
		"alabaster",
		"amber",
		"amethyst purple",
		"aquamarine blue",
		"emerald green",
		"garnet red",
		"jade green",
		"lapis blue",
		"obsidian",
		"olivine",
		"fluorine",
		"onyx black",
		"opal iridescent",
		"peridot green",
		"quartz clear",
		"sapphire blue",
		"topaz yellow",
		"turquoise blue-green",
		"agate brown",
		"malachite green",
		"hematite gray",
		"pyrite gold",
		"rhodonite pink",
		"rose quartz pink",],

	"Pattern" : [
		"zebra print", 
		"rainbow", 
		"leopard", 
		"tiger", 
		"camouflage green",
		],

	"Unclassed" : [
		"alabaster",
		"amaranth",
		"amber",
		"amber",
		"amethyst",
		"anaglyph effect",
		"anaglyph filter",
		"antique steel",
		"aqua",
		"aquamarine",
		"arabian red",
		"asparagus",
		"auburn",
		"auburn",
		"aureolin",
		"azure",
		"baker-miller pink",
		"beige",
		"bismuth",
		"black",
		"blonde",
		"blood orange",
		"blue magenta",
		"blue",
		"blue",
		"blue-green",
		"blue-violet",
		"bondi blue",
		"brass",
		"brick red",
		"bright blue",
		"bright green",
		"bright orange",
		"bright pink",
		"bright purple",
		"bright yellow",
		"bronze",
		"brown",
		"burgundy",
		"burnt orange",
		"burnt sienna",
		"burnt umber",
		"cardinal",
		"carmine",
		"carrot orange",
		"celadon",
		"cerise",
		"cerulean",
		"champagne",
		"charcoal",
		"chartreuse",
		"cheetah print",
		"cherry blossom pink",
		"chestnut",
		"chocolate",
		"chromatic aberration",
		"chrome",
		"cinnabar",
		"cinnamon",
		"cobalt",
		"color blindness",
		"cool blue",
		"cool green",
		"cool indigo",
		"cool orange",
		"cool pink",
		"cool red",
		"cool violet",
		"cool yellow",
		"copper patina",
		"copper verdigris",
		"copper",
		"copper, patina",
		"copper, verdigris",
		"coral",
		"coral",
		"corn",
		"cornflower",
		"cow print",
		"cream",
		"crimson",
		"crimson",
		"cubic zirconia",
		"cyan",
		"cyanotype",
		"cyber noir",
		"dandelion",
		"dark black",
		"dark blue",
		"dark green",
		"dark indigo",
		"dark orange",
		"dark pastel",
		"dark pink",
		"dark rainbow",
		"dark red",
		"dark violet",
		"dark white",
		"dark yellow",
		"dayglo blue",
		"dayglo green",
		"dayglo orange",
		"dayglo pink",
		"dayglo purple",
		"dayglo yellow",
		"dayglo",
		"deep blue",
		"deep green",
		"deep indigo",
		"deep orange",
		"deep pink",
		"deep purple",
		"deep red",
		"deep yellow",
		"denim",
		"diamond",
		"easter red",
		"electric blue",
		"electric color",
		"electric green",
		"electric indigo",
		"electric orange",
		"electric pink",
		"electric purple",
		"electric red",
		"electric yellow",
		"emerald",
		"falu red",
		"fern green",
		"fire",
		"firebrick",
		"flat color",
		"flax",
		"fluorescent blue",
		"fluorescent green",
		"fluorescent orange",
		"fluorescent pink",
		"fluorescent purple",
		"fluorescent yellow",
		"fluorescent",
		"forest green",
		"french rose",
		"fuchsia",
		"full of color",
		"ginger",
		"glittering",
		"gold",
		"gold",
		"golden hour",
		"golden",
		"goldenrod",
		"graphite",
		"gray",
		"green",
		"green",
		"greenery",
		"grey",
		"han blue",
		"han purple",
		"heliotrope",
		"hollywood cerise",
		"hot pink",
		"hunter green",
		"icy",
		"incandescent",
		"indigo",
		"infrared",
		"inverted colors",
		"iridescent",
		"iron",
		"ivory",
		"jade",
		"jade",
		"jet black",
		"kelly green",
		"khaki",
		"lapis lazuli",
		"lavender",
		"lawn green",
		"leather",
		"lemon chiffon",
		"lemon",
		"leopard print",
		"light blue",
		"light green",
		"light indigo",
		"light orange",
		"light pink",
		"light red",
		"light violet",
		"light yellow",
		"lilac",
		"lime green",
		"lime",
		"linen",
		"magenta",
		"magnolia",
		"malachite",
		"maroon",
		"midnight blue",
		"mint green",
		"mint",
		"misty rose",
		"moonstone",
		"moss green",
		"mustard",
		"nacreous",
		"navajo green",
		"navajo red",
		"navajo white",
		"navy blue",
		"navy",
		"neon blue",
		"neon green",
		"neon orange",
		"neon pink",
		"neon purple",
		"neon rainbow",
		"neon yellow",
		"neon",
		"neon",

		"ochre",
		"office green",
		"olive",

		"onyx",
		"opalescent",
		"orange",
		"pale blue",
		"pale green",
		"pale indigo",
		"pale orange",
		"pale pink",
		"pale red",
		"pale",
		"pastel gray",
		"pear",
		"pink",
		"rainbow",
		"redhead",
		"salmon",
		"salt and pepper",
		"scarlet",
		"silver",
		"slate gray",
		"smalt",
		"snow",
		"teal",
		"turquoise",
		"violet",
		"viridian",
		"warm blue",
		"warm green",
		"warm indigo",
		"warm orange",
		"warm pink",
		"warm red",
		"warm violet",
		"warm yellow",
		"white",
		"white",
		"wisteria",
		"yellow",
		"yellow",
		],
};




