const BIB_CLOTHS = {
	"Commons/neutral": [
		"dark outfit",
		"%color lipstick",
		"necklace",
		"long %color coat",
		"dark shirt",
		"%color dress",
		"knot on her hair",
		"oversized cloak",
		"tattered robes",
		"a cowl",
		"torn-up cloths",
		"turtleneck",
		"technical wear",
		"A tight-fitting top with long sleeves and a high collar",
		"A piece of clothing that covers the lower half of the body and is divided into separate leg sections",
		"A short, sleeveless top that exposes the midriff",
		"A full-length garment worn by women that is often formal or semi-formal",
		"A one-piece garment that covers the body from the waist down and includes pants and a shirt",
		"A garment that covers the upper body and has no sleeves",
		"A garment that covers the upper body and has short sleeves",
		"A garment that covers the upper body and has no sleeves or collar",
		"A garment that covers the lower body and has a narrow cut from the waist to the ankle",
		"A garment that covers the lower body and has a wide cut from the waist to the ankle",
		"A garment that covers the lower body and is made of stretchy material",
		"A garment that covers the feet and ankles and is worn for warmth or protection",
		"A garment that covers the feet and ankles and is worn for sports or physical activity",
		"A garment that covers the feet and ankles and is worn for formal occasions",
		"A garment that covers the upper body and has long sleeves and buttons down the front",
		"A garment that covers the upper body and has no sleeves and is worn over the head",
		"A garment that covers the upper body and has long or short sleeves and is worn open or closed",
		"A garment that covers the upper body and has short or long sleeves and is worn open or closed",
		"A garment that covers the lower body and is worn for sports or physical activity",
		],
	"Fantasy": [
		"black horns and pale skin",
		"ram %color horns",
		"cloak",
		"winter jacket",
		"giant monster claws",
		"furry ears",
		"glowing %color eyes",
		"a nice black and gold skirt with crimson ornementations",
		"%material tunic",
		"cloak with magical ornament",
		"robe of spiritual power",
		"mantle adorned with golden lines",
		"surcoat adorned with heraldic symbols",
		"jerkin",
		"doublet with hose",
		"tabard",
		"kirtle",
		"cotehardie",
		"chemise",
		"houppelande",
		"surcote",
		"smock",
		"camise",
		"sarong",
		"sari",
		"kimono",
		"yukata",
		"hanbok",
		],
	"Military":[
		"guns, ",
		"armour",
		"glass armour", 
		"boots",
		"scaly armour",
		"gazmask",
		"skimpy armour",
		"shiny armour",
		"detailed intricate white bone tactical armor",
		"detailed intricate breastplate armor",
		"scifi armor",
		"A black and %color line armour. Big pauldron",
		"An armour with %material greaves",
		"A hi-tech helmet",
		"a metal cap",
		"officer uniform",
		],
	"Formal": [
		"evening gown",
		"evening dress",
		"cocktail dress",
		"little black dress",
		"formal gown",
		"ball gown",
		"prom dress",
		"wedding dress",
		"bridal gown",
		"tuxedo",
		"formal suit",
		"morning suit",
		"dinner jacket",
		"dress shirt",
		"bow tie",
		"cummerbund",
		"lapel pin",
		"pocket square",
		"suspenders",
		"dress shoes",
		],
	"Erotism": [
		"ample cleavage",
		"scarlet lips", 
		"latex corset plus size",
		"shiny black corsets",
		"inflatable black latex", 
		"transparent latex bubble",
		"latex bodysuit",
		"nothing but chains",
		"leather cloth",
		"lingerie",
		"garterbelt",
		"bdsm lingerie",
		"fishnet stockings",
		"inflatable transparent latex",
		"school uniform",
		"see-through cloths",
		"high boots",
		"revealing shredded cloths",
		"panties",
		"long zebred socks",
		"long gloves", 
		"nothing",
		"wet t-shirt",
		"hosiery",
		],
	"Casual": [
		"pajama",
		"robe",
		"skirt",
		"dress",
		"white shirt",
		"%color t-shirt",
		"pantyhose",
		"hosiery",
		"swimsuit",
		"big collar",
		"thick nerdy glasses",
		"one-piece swimsuit",
		"school girls uniform", 
		"black pantyhose, %color skirt and hair"
		],
	"Activity (sport, work)": [
		"sport costume",
		"wedding dress",
		"tight professional suit",
		"office suit",
		"leotard",
		"white lab coat",
		"swim cap",
		"swim goggles",
		"snorkel",
		"athletic shorts",
		"sweatpants",
		"track pants",
		"running tights",
		"leggings",
		"compression shorts",
		"bike shorts",
		"swim trunks",
		"swim briefs",
		"surf trunks",
		"rash guard",
		"wetsuit",
		"drysuit",
		"swim cap",
		"swim goggles",
		"flippers",
		"snorkel",
		"life jacket",
		"jersey",
		"uniform",
		],
	"Fancy & Special": [
		"black opera gloves",
		"flowing, rich, folds, ruffles of fabric",
		"taffeta, chiffon",
		"silk",
		"ripped shorts",
		"haute couture",
		"high fashion",
		"suits and fedora",
		"gossamer frilly lacey dress",
		"kneehigh boots",
		"diadema",
		"rich victorian costume",
		"flared pants",
		"ruffled collar",
		"feathered collar",
		"silver choker necklace",
		"chiffon satin",
		"chain around neck",
		"floral one-piece swimsuit",
		"a dark red robe with silver ornements. Carmin feathers and earrings.",
		"%chara costume",
		],
	"Scifi": [
		"glass helmet",
		"space suit",
		"lots of wires",
		"a suit with leds glowing",
		"a fractal coat",
		"an iridescent coat",
		"a transparent plastic suit with black opaque strips",
		"a sun-reflective material covering the whole body",
		"a bulbous %color mecanical suit with tubes and wires",
		"a simple and geometric suit with some metal plates and %color stripes",
		"light %color filigree bikini armor",
		"luminescent light blue silk cowl",
		"Wires connect everything via suit",
		"shiny futuristic pvc street fashion ",
		],
	"Others": [
		"draped in fine ethereal fabric",
		"pumpkin mask",
		"intricate gothic mask",
		"highwaist pants",
		"a black corset dress", 
		"flowing pastel sakura colored dress",
		"ripped aristocrat attire",
		"english clothing",
		"pantyhose in transparent latex bubble",
		"choker",
		"stilettos",
		"bindi",
		"oxfords",
		"crop top",
		"a black graphic metal tee",
		"a black leather jacket",
		"a heavy futuristic coat",
		"a red onepiece swimsuit",
		"boho black macrame dress",
		"kimono",
		"rimless glasses",
		"silver and orange and black aventurine stone jewlery",
		"white peasant frock with lace",
		"%color jacked",
		"light space armor",
		"stylish tight orange dress",
		"medieval hood",
		"ornate pattern mask with a crown",
		"a black leather pleated miniskirt",
		"a black miniskirt under an oversized baseball jacket",
		"legendary armor",
		"space helmet",
		"the poison ivy costume from batman the animated series",
		"superhero costume",
		"skimpy armour",
		"leather spiky chained armor",
		"white sundress",
		"futuristic scifi armor",
		"headdress and fantasy jewelry",
		"flapper style dress and cloak with intricate beed work. ",
		"fine fancy opulent dressed lady. ",
		"dress with flowing",
		"revealing leaf bikini anime",
		"old worn leather jacket",
		"monster bone armor with fur lining",
		]
};
