const ARTISTS_TAGS_GLOSSARY = {
	"Medium": [
		{tag: "3d", description: "3D", definition:"Image rendered in 3D by a computer."},
		{tag: "anime", description: "Anime", definition:"Japanese animation cartoon"},
		{tag: "digital", description: "Digital", definition:"Made with a computer"},
		{tag: "collage", description: "Collage", definition:""},
		{tag: "architecture", description: "Architecture", definition:"Buildings art"},
		{tag: "graffiti", description: "Graffiti", definition:"Found on the street"},
		{tag: "comics", description: "Comics", definition:"American and non-american format"},
		{tag: "ink", description: "Ink", definition:"Drawing made with black ink and not colored"},
		{tag: "photography", description: "Photography", definition:""},
		{tag: "installation", description: "Installation", definition:""},
		{tag: "sculpture", description: "Sculpture", definition:""},
		{tag: "stained glass", description: "Stained glass", definition:""},
		{tag: "textile", description: "Textile", definition:""},
		{tag: "ukiyoe", description: "Ukiyo-e", definition:""},
		{tag: "watercolor", description: "Watercolor", definition:""},
		{tag: "fashion", description: "Fashion", definition:""},
		],

	"Aspect": [
		{tag: "flatcolors", description: "Flat Colors", definition:""},
		{tag: "geometric", description: "Geometric", definition:""},
		{tag: "glitch", description: "Glitch", definition: "Something feels wrong with this…"},
		{tag: "gore", description: "Gore", definition:""},
		{tag: "highcontrast", description: "High contrast", definition:""},
		{tag: "linedrawing", description: "Line drawing", definition:""},
		{tag: "monochromatic", description: "Monochromatic", definition:""},
		{tag: "lowcontrast", description: "Low contrast", definition:""},
		{tag: "detailed", description: "Detailed", definition:""},
		{tag: "abstract", description: "Abstract", definition:"Nothing is recognisable."},
		],

	"Art movement": [
		{tag: "academism", description: "Academism", definition:""},
		{tag: "artdeco", description: "Art Deco", definition:""},
		{tag: "artnouveau", description: "Art Nouveau", definition:""},
		{tag: "baroque", description: "Baroque", definition:""},
		{tag: "bauhaus", description: "Bauhaus", definition:""},
		{tag: "cubism", description: "Cubism", definition:""},
		{tag: "expressionism", description: "Expressionism", definition:""},
		{tag: "fauvism", description: "Fauvism", definition:""},
		{tag: "futurism", description: "Futurism", definition:""},
		{tag: "graphicdesign", description: "Graphic Design", definition:""},
		{tag: "impressionism", description: "Impressionism", definition:""},
		{tag: "popart", description: "Pop Art", definition:""},
		{tag: "primitivism", description: "Primitivism", definition:""},
		{tag: "realism", description: "Realism", definition:""},
		{tag: "renaissance", description: "Renaissance", definition:""},
		{tag: "surrealism", description: "Surrealism", definition:""},
		{tag: "symbolism", description: "Symbolism", definition:""},
		{tag: "rococo", description: "Rococo", definition:""},
		{tag: "romanticism", description: "Romanticism", definition:""},
		{tag: "magicrealism", description: "Magical Realism", definition:""},
		{tag: "luminism", description: "Luminism", definition:"The light imbue the whole image in a kind of peaceful and transcendental way."},
		],

	"Genre": [
		{tag: "cartoon", description: "Cartoon", definition:""},
		{tag: "children", description: "Children", definition:""},
		{tag: "erotism", description: "Erotism", definition: "this adult theme"},
		{tag: "horror", description: "Horror", definition:""},
		{tag: "fantasy", description: "Fantasy", definition:""},
		{tag: "manga", description: "Manga", definition:""},
		{tag: "scifi", description: "Sci-fi", definition:""},
		{tag: "nudity", description: "Nudity", definition:""},
		],

	"Subjective impression": [
		{tag: "androcentric", description: "Androcentric", definition:""},
		{tag: "clean", description: "Clean", definition:"uncluttered"},
		{tag: "colorful", description: "Colorful", definition:""},
		{tag: "dark", description: "Dark", definition:""},
		{tag: "gynocentric", description: "Gynocentric", definition:""},
		{tag: "messy", description: "Messy", definition:""},
		{tag: "passe", description: "Passé", definition: "A bit old school, passé de mode"},
		{tag: "vibrant", description: "Vibrant", definition:""},
		{tag: "psychedelic", description: "Psychedelic", definition:""},
		{tag: "whimsical", description: "Whimsical", definition:""},
		],

	"Subject" : [
		{tag: "animals", description: "Animals", definition:"Production centered on the representation of animals"},
		{tag: "character", description: "Character", definition:""},
		{tag: "cityscape", description: "Cityscape", definition:""},
		{tag: "cloudscape", description: "Cloudscape", definition:""},
		{tag: "scene", description: "Scene", definition:""},
		{tag: "portrait", description: "Portrait", definition:""},
		{tag: "nature", description: "Nature", definition:""},
		{tag: "seascape", description: "Seascape", definition:""},
		{tag: "space", description: "Space", definition:""},
		{tag: "stilllife", description: "Still life", definition:""},
		{tag: "streetart", description: "Street art", definition:""},
		{tag: "streetscape", description: "Streetscape", definition:""},
		{tag: "landscape", description: "Landscape", definition:""},
		{tag: "light", description: "Light", definition:"source of light well defined"},
		],
};


