const SUBJECTS = {
	"Portraits" : [
		"The portrait of a %adj_chara %character reading one %color book.",
		"The %color %material bust of an %adj_chara %character.",
		"The %adj_chara %character of a %color president.",
		"Portrait of a young %character with a %color hat and a big earing.",
		"An %adj_chara %material sculpture of the head of a %character.",
		"Portrait of a %adj_chara %character holding a baby %animal in her arms.",
		"Side portrait of a %adj_chara %character in rich clothes.",
		"Tilted head of a %adj_chara %character with long dark hair.",
		"Portrait of a %adj_chara %adj_chara %character, holding a purse, barely smiling.",
		"Portrait of a %character in ligh cloth, turning her back on us.",
		"Portrait of a %character wearing a %animal fur around neck.",
		"Royal portrait of a %character, well dressed, posing in the garden.",
		],
	"Scene": [
		"An %adj_chara %character %action.",
		"A %adj_chara %character %action in a %adj_chara watered temple.",
		"Two %adj_chara %character %action.",
		"A %character in a suit %action in a crowded street.",
		"A %adj_chara %character %action, smiling.",
		"A %adj_chara %character %action while his following %character %action.",
		"An %adj_chara %character %action.",
		"Three %character %action, while a fourth is sitting, listening to them.",
		"%character %action. Some %animal running around them.",
		"%adj_chara %character %action. Some %character behind them.",
		"Two %character, %action. Some light on the ground.",
		"A night scene with a group of %adj_chara %character %action next to a big illuminated building.",
		"A %character %action.",
		],
	"Landscapes": [
		"Two %character on a roof. In a distance, a %material tower partially masked by the fog."
		],
	"Vehicule": [
		"A car made of %material, exposed in a place.",
		"A concept drawing of a vegetal hovering vehicule.",
		"An old rusted iron locomotive, buried under vegetation. Light is working.",
		],
	"Building": [
		"A %building with small doors and no window.",
		"A tower made of %material.",
		"A %building made of %material spheres connected by tubes.",
		"A flat %building with %color glass and %material columns.",
		"A high modern %building with round %color metal pieces.",
		"An ancient %building with %material decorations, covered by plants.",
		"It's night. A dark street with a spooky %building. A few lantern light at the windows.",
		// "Some little house with %color roof. Colored small %adj_object windows.",
		// "A %color %adj_object %building with clouds.",
		// "A heavy %color %building made of %material, lost in a %place.",
		// "A %material model of a %adj_object %building complex.",
		// "A dark street with %adj_object appartment and shadows.",
		// "An illuminated %adj_object %building in the street by night. %material columns.",
		// "A small %building alone in a peaceful %place.",
		// "A beach in a sunny %place with nice %building, except one dark %color %building.",
		],
	"Objects": [
		"A %material %object, decorated with a coat of arms, featuring a %animal.",
		"A shiny %object made of %material.",
		"A %object floating into trouble waters.",
		"A %object with bolts and nuts.",
		"A %object in a circle of %object. Priests flexing around it.",
		"An %object falling from a %place in fire.",
		"Schematic blueprint, sketch of a %object with the form of a %chara.",
		"Some old %object in a jar.",
		"A swarm of %object, %object and other %objects parts.",
		"Organic %object, necromechanics.",
		"Surreal mythological %chara %object %material bas relief.",
		"A %object with clothes, jar with liquids, masks, skulls.",
		"A %object with magic aura. Shiny %material.",
		"A %color and %material embroidered gothic medieval dress with elegant pattern.",
		"A %material %object with %object.",
		"Mythical %object in the form of a %chara.",
		// "An old %adj_object book with %material finish.",
		// "Illustration of a %adj_object %material %object.",
		// "Female %adj_object %object.",
		// "A small precious %object in a %adj_object box.",	
		],
	"Medieval drawing": 
	[
		"An illumination depicting a %building with several towers and battlements.",
		"An intricate drawing on a page yellowed with age. A knight on horseback, in full armor, holding a lance.",
		"An illumination in a codex. A woman bath in a bucket. A rabbit watches her.",
		"A drawing in black ink on a parchment or vellum surface.",
		"A wood gravure showing soldiers with spears and bows, and a group of people gathered outside the castle gates.",
		"A copper gravure, depicting a man holding a shield.",
		"A woodcarving, representing death dancing around a rich couple.",
		],
};




/*
--------------------------------
MAIN SUBJECTS
--------------------------------
A %adj_place %adj_place landscape of [geographic location].
A %adj_chara %character in a %adj_chara environment. 
A %adj_chara %character in its natural habitat. 
A %adj_chara %character wearing [clothing], 
A %adj_chara %character.
A %adj_chara %character, dressed in [clothing], standing in front of a %adj_chara background.
A %adj_chara %character, in a %adj_chara setting.
A %adj_chara %character, with %adj_chara details and %adj_chara features.
A design of a %adj_chara %character with %adj_chara accessories, in a %adj_chara environment.
A design of a %adj_chara %character.
A group of %adj_chara %adj_chara %character.
A landscape of a %adj_chara %adj_chara [setting].
A panoramic view of a %adj_chara %adj_chara [natural feature].
A portrait of a %adj_chara %character in a %adj_chara setting.
A portrait of a %adj_chara %character with %adj_chara features, in a %adj_chara setting.
A scene featuring a %adj_chara %character in a %adj_chara environment.

-----------------------------------
PORTRAITS
-----------------------------------
	"Picture of a family of %adj_chara %chara",
	"Picture of friends",
	"Picture of a %chara celebrity",
	"Picture of an historical figure",
	"Picture of a %adj_chara pet",
	"Picture of a %adj_chara %chara children",
	"Picture of an elderly %chara",
	"Picture of a %adj_chara musician",
	"Picture of a %chara artist",
	"Picture of a %adj_chara political leader",
	"Picture of a business leader",
	"Picture of a %chara teacher",
	"Picture of a %adj_chara sports figure",
	"Picture of a %adj_chara writer",
	"Picture of an actor or actress",
	"Picture of a military personnel",
	"Picture of a %adj_chara religious figure",
	"Picture of a %adj_chara scientist",
	"Picture of a %adj_chara philosopher",
	"Picture of a %adj_chara royalty",
	"Picture of a %adj_chara activist",
	"Picture of a %chara environmentalist",
	"Picture of a %adj_chara performer",
	"Picture of a mythical %chara",
	"Close-up of a %material and %material sculpture of a %adj_chara %chara.",
	"A crying bereaved %adj_chara %chara, with black %cloth, holding a dying child.",
	"%adj_chara warrior %chara, %hair, gorgeous, juicy, curvy, voluptuous, bending over.",
	"Gorgeous %adj_chara %adj_chara %chara in 3D.",
	"An %adj_chara %color %chara clothed, %color skin %chara with %color eyes.", 
	"portrait of a %adj_chara %color skin punk %adj_chara %chara, ruffled collar, long hair.",
	"Portrait of a %adj_chara %adj_chara %chara with bare shoulders holding a %color %material flower.",
	"Portrait of a %adj_chara %chara.", 
	"Full body design in relief of the %adj_chara %chara.",
	"Detailed picture of a %adj_chara %chara with %cloth.",
	"Portrait painting of a posing %chara %chara hybird.",
	"A pirate %chara holding cutlass and posing with a parrot on shoulder.",
	"Ancient %adj_chara %chara wearing %cloth with %cloth with straight ruby red hair on a sunny day. ",
	"Traditionnal portrait of a %chara living underwater.",
	"A candid portrait of an old %material %chara.",
	"Face of a winged angel and devil brother.",
	"A %color and %color %chara.",
	"Self-portrait of a %chara holding a white %material stick in hand.",
	"Close-up portrait of a %chara eating a candy",
	"The portrait of a young blonde %chara, with %cloth, %hair, a %color streak of hair.",
	"Small %chara with dusty %color hair and large, shining %color eyes.",
	"The bust of a %chara with %color %cloth, %hair.",
	"Submissive %chara, fetish model, bizarre, taboo, leather, latex, rubber",
	"Egyptian %chara dressed in %color and %color fabric.",
	"%chara dressed for halloween, long orange hair.",
	"Seductive young %chara. Hollow dark eyes, missing limb, ripped clothes, cheekbones.",
	"Profile portrait of a %chara with %cloth, and earrings.",
	"Portrait of a %adj_chara %chara with %cloth and skull.",
	"Two sapphic lesbian %chara in light %color robes, in the clouds.",
	"Front face, visage cut in half, part %chara, part %chara.",
	"Closeup on face of an half %chara with peeling skin. Few hair.",
	"Portrait art of cyberpunk dark %chara with cyberglasses, suggestive outfit design.",
	"Teatcher %chara in a mysterious class room, sitting with closed eyes.",
	"Young %actor as a graphic novel female protagonist.",
	"A time traveller %chara in a futuristic suit.",
	"A portrait of a shy, blushing %chara wearing bikini bottom with ripped shorts.",
	"The face of a dirty %chara during the day. Wrench and Tools.",
	"Biomechanical young female %chara with a %material face.",
	"Face of a short-haired %chara in an elaborate %cloth. She's in and observatory with telescope and microscopes.",
	"Portrait of a %chara in a plant conservatory like Kew Garden. Exotic plants, impressive foliage.",
	"Unhappy %adj_chara %chara, standing in a desert.", 
	"%adj_chara %chara wearing rich %cloth on his %material throne, with a holy artefact.",
	"Portrait of a young fallen %chara with %color and %color long hair.",
	"Native exotic country %chara, innocently erotic, %color hair, big bosom, sitting on rice terraces, stripped skirt, bead neaklace.",
	"Gothic %chara face with golden glowing eyes. Shiny hair, smooth pale skin, war facepaint.",
	"Goth female %chara. Toned arms. Dressed like a Valkyrie.",
	"A portrait of a african %chara, ottoman empire, plump lips, royal clothes with golden jewelry.",
	"%adj_chara %adj_chara %chara with %hair, wearing %cloth with %cloth on a sunny day.",
	"Lovely curvy %adj_chara %chara with ample bosom.",
	"A young %chara in ballet leotard. She's svelte, slender. Nose bleeding.",
	"%chara in %cloth wearing a gothic mask.",
	"%color oil paiting portrait of a %chara in %cloth.",
	"In a %place, a female %chara with antlers, covered in mud and entrails",
	"%chara with big %color eyes. Sad smile. %cloth.",
	"%adj_chara %chara with big belly showing. %cloth letting the bely visible.",
	"Extravagant dark fantasy %adj_chara %chara girl model with bright %color %hair.",
	"A noble %chara posing in front of %color pattern wall.",
	"Photo of a %adj_chara %chara with %hair wearing %cloth.",
	"A %adj_chara %chara in a %material %place.",
	"Portrait of a %adj_chara %adj_chara %chara with %hair",
	"A %material %chara on stage. %color and %color lights. %chara in suggestive suits.",
	"Profile portrait %chara wearing %cloth.",
	"Portrait of a %chara underwater, in a swimming pool made of %material and %material.",
	"A %adj_chara %color %chara with %hair. A fireball in hands.",
	"Viewed through a %adj_chara window, a %chara standing on a railing.",
	"A %adj_chara %adj_chara %chara with big eyes and pregnant wet %chara twins on the ground.",
	"%adj_chara %chara with fireflies and dust and glitter and sun ray in air.",
	"A picture of an %adj_chara %color woman with %hair, observing the city from a window.",
	"Fine %adj_chara %adj_chara %chara. Dressed with %cloth and %cloth.",
	"Portrait of an %adj_chara %chara in a %cloth with dark %color hair %color skin.",
	"Portrait of two kissing %adj_chara %chara with %hair wearing wedding %cloth.",
	"Portrait of two expressive %adj_chara %chara in %cloth hand in hand.",
	"Group photo of sport swim team wearing %cloth",
	"Stained Glass portrait of a %chara girl",
	"Two %adj_chara %chara with %hair wearing %cloth",
	"A young boy and girl, prince and princess in a %place.",
	"A cute %chara, creature of darkness with big cutes cat eyes.",
	"A erotic oil painting of a %adj_chara %adj_chara %chara ",

-------------------------------
SCENES
-------------------------------
"A %chara is standing in front of the %building. It had %hair, %color eyes, and %adj_chara characteristics.",
	"A %chara is sitting under the shade of a %plant in %place. It had %color hair, %adj_chara personality, and is wearing %cloths.",
	"A %adj_chara %chara lost in a %adj_object %building.",
	"A %adj_chara %chara praying in a %place.",
	"A sporty %chara crawling in a narrow %place",
	"A female %chara %action in a %adj_object %building",
	"A %chara in the center of a %place, on television set.",
	"A black and white photography in a newspaper of a %chara %action.",
	"A %chara %action in a television studio.",
	"In a %place, some %adj_chara %chara are %action",
	"A small group of %adj_chara %chara, %action.",
	"A large groupe of %adj_chara %chara, %action.",
	"A dining table of %chara, enjoying a meal.",
	"Four %chara, praying in circle.",
	"Acting as one, three %adj_chara %chara are %action",
	"A %chara in an artificial womb, some %chara cleaning the place.",
	"A frighteningly horrific %adj_chara %chara %action.",
	"A group of %adj_chara %chara.",
	"Two %adj_chara %adj_chara %chara %action.",
	"Some skelettons of dead warriors %action.",
	"Sport swim %chara team wearing %cloth %action.",
	"%adj_chara %chara in %cloth %action.",
	"A %chara with %hair %action.",
	"%adj_chara %chara with long %color %hair %action.",
	"A %chara in a suit %action.",
	"A %chara %action.",
	"Two %chara %action.",
	"Three angry %chara %action.",
	"Four %chara, %action.",
	"Blonde %chara in %color dress %action.",
	"A %adj_chara %chara smiling, %action.",
	"Love couple %adj_chara %chara %action.",
	"A %adj_chara %adj_chara %chara with %hair %action.",
	"Silhouette of a %chara and a %chara %action.",
	"two %adj_chara %chara, egyptian gods, ankh staff, %action.",
	"Two %adj_chara %chara %action.",
	"A hugging couple of %chara in a crowd.",
	"A silly smiling %chara, %action. She's intense.",
	"A group of %adj_chara %chara in a cave, fighting.",
	"A %chara in %color clothes %action.",
	"A %color %chara %action.",
	"A flock of young puppy %chara %action.",
	"Four %chara in the center of a %place, cerned by crowd of armed %chara, %material weapons ready.",
	"Two young %chara %action. They are in a dark forest %action.",
	"A %chara %action, in a room full of people watching.",
	"A %chara %action. A panicked young %chara behind.",
	"Some %chara %action. Blood on the wall. Bruise and ripped clothes.",
	"A nude %chara in an artistic painter workshop. Men with mustaches talking.",
	"Celestial dark %chara, %action.",
	"A %chara %action, over a giant %material mushroom.",
	"A young %chara, %action, under a ray of light in the dark ruin of a church.",
	"A %adj_chara %chara, grotesque and horrifying, %action.",
	"Two %chara wearing %color %cloth %action.",
	"Black african %chara in the %place, %action.",
	"Tall and large angelic blonde %chara %action.",
	"An albino %chara in black bride robe %action.",
	"A young %chara %action. He seems in shock. There is blood on his face.",
	"A %chara, %color long coat, %color scarf, %action, near a haunted house.",
	"A %chara, a %chara and a %chara are on a boat. One of them fall in the water…",




-------------------------------
ANIMALS
-------------------------------
const myAnimalsSchemes = [
	"A prehistoric %adj_chara %chara lurking in a cave",
	"A demonic %chara, invoqued in a %place by a %adj_chara %chara",
	"A fantastic %adj_chara %adj_chara flying in the night",
	"A mechanical %chara and a %adj_chara %chara",
	"A fantastical %adj_chara %chara in a %place",
	"A medieval %adj_chara %chara beast, %action",
	"A %chara sleeping on a cushion.",
	"A %chara dying at the bottom of a fish tank.",
	"A %adj_chara %chara four-legged creature running in thermal waters sources.",
	"A furry though %chara missing one leg. Many scars. ",
	"A %adj_chara critter with shiny %color carapace.",
	"A %adj_chara %chara hunting a %chara prey.",
	"A %chara sleeping under a %plant.",
	"A %chara with blood on face, eating the guts of a %chara, cage rib open.",
	"A group of %adj_chara %chara drinking water on a lake.",
	"A flock of flying %chara.",
	"In a %place, a male %chara reproducing with a female %chara, under the shadow of a tree.",
	"A very old %chara walking in an animal cemetery. Bones dressed.",
	];



*/